### ISSUE TITLE
uncaughtException: cb is not a function

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p#1158]
Lodestar users have reported issues with libp2p's dependency nat-api

See https://github.com/ChainSafe/lodestar/issues/2996

```
TypeError: cb is not a function
    at /home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/@motrix/nat-api/index.js:324:16
    at Request._callback (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/@motrix/nat-api/lib/upnp/device.js:46:25)
    at self.callback (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/request/request.js:185:22)
    at Request.emit (node:events:520:28)
    at Request.emit (node:domain:475:12)
    at Request.onRequestError (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:520:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:520:28) message=cb is not a function
```

Does Nat manager do any other vital task besides calling UPnP to open ports? What are the consequences of disabling it?

**Comment by dapplion** [comment]
@twopercent Thanks! Are you running Mainnet or Prater?

If you are running a testnet you can run the latest nightly build which includes a fix [#3761](https://github.com/ChainSafe/lodestar/pull/3761) . Note that this release is not guaranteed to be stable https://hub.docker.com/layers/chainsafe/lodestar/next/images/sha256-176030b7081b9409e8b84302eb50ba4fc4703d62e42dc76dabcdc85b12def65e?context=explore

**Comment by twopercent** [comment]
Mainnet.

It has been running for most of today so I will leave it. If it crashes again, I will fire up a testnet with the fix.

**Comment by dapplion** [comment]
> Mainnet.
> 
> It has been running for most of today so I will leave it. If it crashes again, I will fire up a testnet with the fix.

Then stay at your current version. This error is just an annoyance should not cause issues to the node performance. However we merged this PR so in the next stable release you will not see this errors again? https://github.com/ChainSafe/lodestar/pull/3761
