### ISSUE TITLE
[ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "libp2p".

### ISSUE THREAD

**Issue by jellllly420** [libp2p/js-libp2p#1273]
- **Version**:

0.37.3

- **Platform**:

Ubuntu 20.04LTS on wsl2

#### Severity:

High

#### Description:

I tried to run the example libp2p-in-the browser following the README.
However, vite threw an error after I run `npm start`. Details are as below:
```bash
jelly@LAPTOP-1PJUJR5C:~/js-libp2p/examples/libp2p-in-the-browser$ npm start

> libp2p-in-browser@1.0.0 start
> vite


  vite v2.9.12 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 144ms.

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "libp2p". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "libp2p". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40945:10:
      40945 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40945:11)
    at resolvePackageEntry (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40941:9)
    at tryNodeResolve (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40748:20)
    at Context.resolveId (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40556:28)
    at Object.resolveId (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39229:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39441:26)
    at async /home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39601:34
    at async callback (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:921:28)
    at async handleRequest (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:701:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39591:18:
      39591 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39591:19)
    at handlePlugins (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:843:23)
    at Object.buildOrServe (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:1137:7)
    at /home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:2085:17
    at new Promise (<anonymous>)
    at Object.build (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:2084:14)
    at Object.build (/home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/esbuild/lib/main.js:1931:51)
    at /home/jelly/js-libp2p/examples/libp2p-in-the-browser/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39389:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    index.js:1:29:
      1 │ import { createLibp2p } from 'libp2p'
        ╵                              ~~~~~~~~

Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40945:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "libp2p". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "libp2p". The package may have incorrect main/module/exports specified in its package.json.
^C
```
![2022-06-24](https://user-images.githubusercontent.com/64725601/175528888-6d36c99e-3400-461d-9592-655990dcbd0c.png)
I expected it could run correctly without throwing out an error.
I noticed a same issue #1242 closed but no help.
Thanks to anyone who is willing to help.

#### Steps to reproduce the error:

```bash
git clone https://github.com/libp2p/js-libp2p.git
cd js-libp2p/
npm install
cd examples/libp2p-in-the-browser/
npm install
npm start
```

**Comment by achingbrain** [comment]
You may need to run:

```
...
cd js-libp2p/
npm install
npm run build      <----- run this
cd examples/libp2p-in-the-browser/
...
```

**Comment by jellllly420** [comment]
> You may need to run:
> 
> ```
> ...
> cd js-libp2p/
> npm install
> npm run build      <----- run this
> cd examples/libp2p-in-the-browser/
> ...
> ```

Thanks!!
