### ISSUE TITLE
Failed to upgrade outbound connection RangeError: index is out of bounds (browser, websockets)

### ISSUE THREAD

**Issue by fryorcraken** [libp2p/js-libp2p#1319]
- **Version**: 0.37.3-05e8e7e

```
▶ npm ls libp2p uint8arraylist @libp2p/websockets @libp2p/multistream-select
js-waku@0.24.0 /home/fryorcraken/src/status-im/js-waku
├─┬ @chainsafe/libp2p-gossipsub@3.4.0
│ └─┬ @libp2p/pubsub@3.1.0
│   ├─┬ @libp2p/interface-pubsub@2.0.0
│   │ └── uint8arraylist@2.3.1 deduped
│   ├─┬ it-length-prefixed@8.0.2
│   │ └── uint8arraylist@2.3.1 deduped
│   └── uint8arraylist@2.3.1
├─┬ @chainsafe/libp2p-noise@7.0.3
│ ├─┬ it-length-prefixed@8.0.2
│ │ ├─┬ uint8-varint@1.0.2
│ │ │ └── uint8arraylist@2.0.0
│ │ └── uint8arraylist@2.3.1 deduped
│ ├─┬ it-pb-stream@2.0.1
│ │ ├─┬ it-length-prefixed@8.0.2
│ │ │ └── uint8arraylist@2.3.1 deduped
│ │ └── uint8arraylist@2.3.1
│ ├─┬ protons-runtime@2.0.2
│ │ ├─┬ byte-access@1.0.1
│ │ │ └── uint8arraylist@2.0.0
│ │ ├─┬ longbits@1.1.0
│ │ │ └── uint8arraylist@2.0.0
│ │ └── uint8arraylist@2.3.1 deduped
│ └── uint8arraylist@2.3.1
├─┬ @libp2p/crypto@1.0.2
│ └─┬ protons-runtime@2.0.2
│   └── uint8arraylist@2.3.1
├─┬ @libp2p/mplex@4.0.1
│ └── uint8arraylist@1.5.1
├── @libp2p/websockets@3.0.1
├─┬ it-length-prefixed@7.0.1
│ └── uint8arraylist@1.5.1 deduped
├─┬ libp2p@0.37.3-05e8e7e
│ ├─┬ @libp2p/multistream-select@2.0.2
│ │ ├─┬ it-length-prefixed@8.0.2
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ ├─┬ it-reader@6.0.1
│ │ │ └── uint8arraylist@2.3.1
│ │ └── uint8arraylist@2.3.2
│ ├─┬ @libp2p/peer-store@3.1.1
│ │ ├─┬ @libp2p/interface-record@2.0.0
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ ├─┬ @libp2p/peer-record@4.0.0
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ ├─┬ protons-runtime@2.0.2
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ └── uint8arraylist@2.3.2
│ └─┬ it-handshake@4.1.0
│   └── uint8arraylist@2.3.1
└─┬ protons-runtime@1.0.4
  └── uint8arraylist@1.5.1 deduped
```

- **Platform**: 
  - `Linux 5.18.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
  - Chromium Version 103.0.5060.134 (Official Build) (64-bit)

- **Subsystem**: `@libp2p/websockets`/`@libp2p/multistream-select`

#### Description:

Using libp2p in the browser, getting the following error. Using websocket for transport (see list- **Version**: 0.37.3-05e8e7e

```
▶ npm ls libp2p uint8arraylist @libp2p/websockets @libp2p/multistream-select
js-waku@0.24.0 /home/fryorcraken/src/status-im/js-waku
├─┬ @chainsafe/libp2p-gossipsub@3.4.0
│ └─┬ @libp2p/pubsub@3.1.0
│   ├─┬ @libp2p/interface-pubsub@2.0.0
│   │ └── uint8arraylist@2.3.1 deduped
│   ├─┬ it-length-prefixed@8.0.2
│   │ └── uint8arraylist@2.3.1 deduped
│   └── uint8arraylist@2.3.1
├─┬ @chainsafe/libp2p-noise@7.0.3
│ ├─┬ it-length-prefixed@8.0.2
│ │ ├─┬ uint8-varint@1.0.2
│ │ │ └── uint8arraylist@2.0.0
│ │ └── uint8arraylist@2.3.1 deduped
│ ├─┬ it-pb-stream@2.0.1
│ │ ├─┬ it-length-prefixed@8.0.2
│ │ │ └── uint8arraylist@2.3.1 deduped
│ │ └── uint8arraylist@2.3.1
│ ├─┬ protons-runtime@2.0.2
│ │ ├─┬ byte-access@1.0.1
│ │ │ └── uint8arraylist@2.0.0
│ │ ├─┬ longbits@1.1.0
│ │ │ └── uint8arraylist@2.0.0
│ │ └── uint8arraylist@2.3.1 deduped
│ └── uint8arraylist@2.3.1
├─┬ @libp2p/crypto@1.0.2
│ └─┬ protons-runtime@2.0.2
│   └── uint8arraylist@2.3.1
├─┬ @libp2p/mplex@4.0.1
│ └── uint8arraylist@1.5.1
├── @libp2p/websockets@3.0.1
├─┬ it-length-prefixed@7.0.1
│ └── uint8arraylist@1.5.1 deduped
├─┬ libp2p@0.37.3-05e8e7e
│ ├─┬ @libp2p/multistream-select@2.0.2
│ │ ├─┬ it-length-prefixed@8.0.2
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ ├─┬ it-reader@6.0.1
│ │ │ └── uint8arraylist@2.3.1
│ │ └── uint8arraylist@2.3.2
│ ├─┬ @libp2p/peer-store@3.1.1
│ │ ├─┬ @libp2p/interface-record@2.0.0
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ ├─┬ @libp2p/peer-record@4.0.0
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ ├─┬ protons-runtime@2.0.2
│ │ │ └── uint8arraylist@2.3.2 deduped
│ │ └── uint8arraylist@2.3.2
│ └─┬ it-handshake@4.1.0
│   └── uint8arraylist@2.3.1
└─┬ protons-runtime@1.0.4
  └── uint8arraylist@1.5.1 deduped
```

- **Platform**: 
  - `Linux 5.18.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
  - Chromium Version 103.0.5060.134 (Official Build) (64-bit)

- **Subsystem**: `@libp2p/websockets`/`@libp2p/multistream-select`

#### Description:

Using libp2p in the browser, getting the following error. Using websocket for transport (see list of libraries above)

```
libp2p:upgrader:error Failed to upgrade outbound connection +466ms RangeError: index is out of bounds
    at findBufAndOffset (index.ts:9:1)
    at Uint8ArrayList.get (index.ts:91:1)
    at read (multistream.ts:71:1)
    at async Module.readString (multistream.ts:79:1)
    at async select (select.ts:29:1)
    at async Dialer.select (index.ts:41:1)
    at async DefaultUpgrader._encryptOutbound (upgrader.ts:581:1)
    at async DefaultUpgrader.upgradeOutbound (upgrader.ts:271:1)
    at async WebSockets.dial (index.ts:48:1)
    at async DefaultTransportManager.dial (transport-manager.ts:115:1)
```

#### Steps to reproduce the error:
Current reproduction is a bit convoluted. Will try to play with the libp2p browser example and see if I can reproduce.

 of libraries above)

```
libp2p:upgrader:error Failed to upgrade outbound connection +466ms RangeError: index is out of bounds
    at findBufAndOffset (index.ts:9:1)
    at Uint8ArrayList.get (index.ts:91:1)
    at read (multistream.ts:71:1)
    at async Module.readString (multistream.ts:79:1)
    at async select (select.ts:29:1)
    at async Dialer.select (index.ts:41:1)
    at async DefaultUpgrader._encryptOutbound (upgrader.ts:581:1)
    at async DefaultUpgrader.upgradeOutbound (upgrader.ts:271:1)
    at async WebSockets.dial (index.ts:48:1)
    at async DefaultTransportManager.dial (transport-manager.ts:115:1)
```

#### Steps to reproduce the error:
Current reproduction is a bit convoluted. Will try to play with the libp2p browser example and see if I can reproduce.

**Comment by fryorcraken** [comment]
Fixed by upgrading to latest version
