### ISSUE TITLE
Not able to Dial Node due to error: ERR_MUXER_UNAVAILABLE

### ISSUE THREAD

**Issue by shishirhome** [libp2p/js-libp2p#1348]
Hi Team

We are getting this error while dialling a node:

Environment:
- Node.js v16.14.0.
- MacBook Pro, Processor 2 GHz Quad-Core Intel Core i5, 16 GB

`import { createLibp2p } from 'libp2p'
import { TCP } from '@libp2p/tcp'
import { Noise } from '@chainsafe/libp2p-noise'
import { Mplex } from '@libp2p/mplex'
import { toString as uint8ArrayToString } from 'uint8arrays/to-string'
import { fromString as uint8ArrayFromString } from 'uint8arrays/from-string'
import { pipe } from 'it-pipe'
import toBuffer from 'it-to-buffer'

const createNode = async () => {
  const node = await createLibp2p({
    addresses: {
      // To signal the addresses we want to be available, we use
      // the multiaddr format, a self describable address
      listen: ['/ip4/0.0.0.0/tcp/0']
    },
    transports: [new TCP()],
    connectionEncryption: [new Noise()],
    streamMuxers: [new Mplex()]
  })

  await node.start()
  return node
}

function printAddrs (node, number) {
  console.log('node %s is listening on:', number)
  node.getMultiaddrs().forEach((ma) => console.log(ma.toString()))
}

;(async () => {
  const [node1, node2] = await Promise.all([
    createNode(),
    createNode()
  ])

  printAddrs(node1, '1')
  printAddrs(node2, '2')

  node2.handle('/print', async ({ stream }) => {
    const result = await pipe(
      stream,
      async function * (source) {
        for await (const list of source) {
          yield list.subarray()
        }
      },
      toBuffer
    )
    console.log(uint8ArrayToString(result))
  })

  await node1.peerStore.addressBook.set(node2.peerId, node2.getMultiaddrs())

  const stream = await node1.dialProtocol(node2.peerId, '/print')
  await pipe(
    ['Hello', ' ', 'p2p', ' ', 'world', '!'].map(str => uint8ArrayFromString(str)),
    stream
  )
})();`

Error Message:

`libp2p:upgrader:error Failed to upgrade outbound connection AbortError: The operation was aborted
    at nextAbortHandler (file:///Users/AK/Desktop/Crypto2/libp2p/node_modules/abortable-iterator/dist/src/index.js:24:32)
    at AbortSignal.abortHandler (file:///Users/AK/Desktop/Crypto2/libp2p/node_modules/abortable-iterator/dist/src/index.js:11:17)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:589:26)
    at abortSignal (node:internal/abort_controller:283:10)
    at AbortController.abort (node:internal/abort_controller:314:5)
    at AbortSignal.onAbort (/Users/AK/Desktop/Crypto2/libp2p/node_modules/any-signal/index.js:11:16)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:589:26)
    at abortSignal (node:internal/abort_controller:283:10) {
  type: 'aborted',
  code: '**ERR_MUXER_UNAVAILABLE**'
} +0ms`

**Comment by shishirhome** [comment]
I got this fixed by downgrading the libp2p version:

npm i libp2p@0.37.3-6630cb1

Thanks
Shishir
