### ISSUE TITLE
js-libp2p npm run build

### ISSUE THREAD

**Issue by Zero-Qi** [libp2p/js-libp2p#1354]
git clone js-libp2p
npm install 
npm run build 

```shell
PS C:\Users\xxq\Desktop\js-libp2p> npm run build

> libp2p@0.37.3 build C:\Users\xxq\Desktop\js-libp2p
> aegir build

ReferenceError: EventTarget is not defined
    at async main (file:///C:/Users/xxq/Desktop/js-libp2p/node_modules/aegir/src/index.js:48:22)
file:///C:/Users/xxq/Desktop/js-libp2p/node_modules/aegir/src/index.js:34
  throw err
  ^

Error: Error finding your config file.
    at config (file:///C:/Users/xxq/Desktop/js-libp2p/node_modules/aegir/src/config/user.js:176:11)
    at async main (file:///C:/Users/xxq/Desktop/js-libp2p/node_modules/aegir/src/index.js:48:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libp2p@0.37.3 build: `aegir build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libp2p@0.37.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxq\AppData\Roaming\npm-cache\_logs\2022-08-15T06_55_56_859Z-debug.log
```

**Comment by mpetrunic** [comment]
@Zero-Qi What versions of nodejs are you using?

**Comment by BigLep** [comment]
Closing since didn't receive input.

**Comment by iliyaZelenko** [comment]
Same on Node `v14.18.1`
