### ISSUE TITLE
DHT example not working

### ISSUE THREAD

**Issue by bakhshandeh** [libp2p/js-libp2p#1419]
I am trying to store something in DHT.
Here is the code:

```
import { createLibp2p } from 'libp2p'
import { TCP } from '@libp2p/tcp'
import { Mplex } from '@libp2p/mplex'
import { Noise } from '@chainsafe/libp2p-noise'
import { CID } from 'multiformats/cid'
import { KadDHT } from '@libp2p/kad-dht'
import all from 'it-all'
import last from 'it-last'
import delay from 'delay'
import drain from 'it-drain'
import { fromString as uint8ArrayFromString } from 'uint8arrays/from-string'

const createNode = async () => {
  const node = await createLibp2p({
    addresses: {
      listen: ['/ip4/0.0.0.0/tcp/0']
    },
    transports: [new TCP()],
    streamMuxers: [new Mplex()],
    connectionEncryption: [new Noise()],
    dht: new KadDHT(),

    config: {
      dht: {
        enabled: true
      }
    }
  })

  await node.start()
  return node
}

;(async () => {
  const [node1, node2, node3] = await Promise.all([
    createNode(),
    createNode(),
    createNode()
  ])

  await node1.peerStore.addressBook.set(node2.peerId, node2.getMultiaddrs())
  await node2.peerStore.addressBook.set(node3.peerId, node3.getMultiaddrs())

  await Promise.all([
    node1.dial(node2.peerId),
    node2.dial(node3.peerId)
  ])

  // Wait for onConnect handlers in the DHT
  await delay(3000)

  const key = uint8ArrayFromString('/v/hello')
  const value = uint8ArrayFromString('world')

  await drain(node1.dht.put(key, value))

  await delay(1000)

  let res = await last(node1.dht.get(key));
  console.log('res', res, res.value);
})();
```

dht.get is not working and the output is this:

```
{
  from: Ed25519PeerIdImpl [PeerId(12D3KooWP8w4GA7QM5VmVd9RLqHMi5KPi64d6jesxEhbL5pTHYME)] {
    type: 'Ed25519',
    multihash: Digest {
      code: 0,
      size: 36,
      digest: <Buffer 08 01 12 20 c5 e9 ....>,
      bytes: [Uint8Array]
    },
    privateKey: <Buffer 08 01 12 40 8f...>,
    publicKey: <Buffer 08 01 12 20 c5 ..>
  },
  error: Error: Not found
      at KadDHT.get (file:///dht/node_modules/@libp2p/kad-dht/dist/src/dual-kad-dht.js:114:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async last (/dht/node_modules/it-last/index.js:13:20)
      at async file:///dht/test.js:59:13 {
    code: 'ERR_NOT_FOUND'
  },
  name: 'QUERY_ERROR',
  type: 3
} 
```

Dependencies:

```
    "@chainsafe/libp2p-noise": "^9.0.0",
    "@libp2p/kad-dht": "^4.0.0",
    "@libp2p/mplex": "^6.0.2",
    "@libp2p/tcp": "^4.0.1",
    "async": "^3.2.4",
    "delay": "^5.0.0",
    "it-last": "^1.0.6",
    "libp2p": "^0.39.5",
    "libp2p-mplex": "^0.10.7",
    "libp2p-switch": "^0.43.0",
    "libp2p-tcp": "^0.17.2",
    "peer-book": "^0.9.2",
    "uint8arrays": "^3.1.0"

```

**Comment by bakhshandeh** [comment]
> In the above example you are using a custom key prefix `/v`:
> 
> ```js
> const key = uint8ArrayFromString('/v/hello')
> ```
> 
> In order to do this, you need to specify [validators](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-dht/src/index.ts#L208-L211) and [selectors](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-dht/src/index.ts#L203-L206) for this prefix:
> 
> ```js
> import { createLibp2p } from 'libp2p'
> import { tcp } from '@libp2p/tcp'
> import { mplex } from '@libp2p/mplex'
> import { noise } from '@chainsafe/libp2p-noise'
> import { kadDHT } from '@libp2p/kad-dht'
> import last from 'it-last'
> import delay from 'delay'
> import drain from 'it-drain'
> import { fromString as uint8ArrayFromString } from 'uint8arrays/from-string'
> 
> const createNode = async () => {
>   const node = await createLibp2p({
>     addresses: {
>       listen: ['/ip4/0.0.0.0/tcp/0']
>     },
>     transports: [tcp()],
>     streamMuxers: [mplex()],
>     connectionEncryption: [noise()],
>     dht: kadDHT({
>       validators: {
>         v: () => {
>           return true // this record is always valid
>         }
>       },
>       selectors: {
>         v: () => {
>           return 0    // when multiple records are found for a given key, just select the first one
>         }
>       }
>     })
>   })
> 
>   await node.start()
>   return node
> }
> 
> ;(async () => {
>   const [node1, node2, node3] = await Promise.all([
>     createNode(),
>     createNode(),
>     createNode()
>   ])
> 
>   await node1.peerStore.addressBook.set(node2.peerId, node2.getMultiaddrs())
>   await node2.peerStore.addressBook.set(node3.peerId, node3.getMultiaddrs())
> 
>   await Promise.all([
>     node1.dial(node2.peerId),
>     node2.dial(node3.peerId)
>   ])
> 
>   // Wait for onConnect handlers in the DHT
>   await delay(3000)
> 
>   const key = uint8ArrayFromString('/v/hello')
>   const value = uint8ArrayFromString('world')
> 
>   await drain(node1.dht.put(key, value))
> 
>   await delay(1000)
> 
>   let res = await last(node1.dht.get(key));
>   console.log('res', res, res.value);
> })();
> ```
> 
> By default libp2p only has validators and selectors for the `/pk` prefix. IPFS, for example, [adds validators and selectors](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/libp2p.js#L156-L161) for the `/ipns` prefix.

It's working fine. Thanks @achingbrain 
It is good to document this somewhere or add an example. I like to contribute if you have any suggestions.
