### ISSUE TITLE
Use of Promise.any() can cause unhandled promise rejection 

### ISSUE THREAD

**Issue by inverted-capital** [libp2p/js-libp2p#1587]
- **Version**: 0.42.2

- **Platform**: Linux plain 6.1.10-100.fc36.x86_64 

- **Subsystem**:  Dialer

#### Description:
On this line: https://github.com/libp2p/js-libp2p/blob/de73b6a22c7580d2bba5ca97f86465c8f9ed0e06/src/connection-manager/dialer/dial-request.ts#L85 there is a call to `Promise.any()` however inside the promises that are supplied to that call, there appears to be insufficient error handling.  Once the call to any has resolved, any of the other promises may still reject and will cause a node system error.  This issue has been raised before: https://github.com/nodejs/node/issues/43639

This is the error I get back when I run [this test](https://github.com/dreamcatcher-tech/dreamcatcher-stack/blob/ea49390c62ceb2b5083f97c47a7202fc75c2bc49/pkg/interblock/src/w310-interpulse/test/mount.test.js#L75):
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[AggregateError: All promises were rejected] {
  code: 'ERR_TIMEOUT',
  [errors]: [
    AbortError: The operation was aborted
        at EventTarget.onAbort (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/@libp2p/websockets/src/index.ts:87:16)
        at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
        at EventTarget.dispatchEvent (node:internal/event_target:677:26)
        at abortSignal (node:internal/abort_controller:308:10)
        at AbortController.abort (node:internal/abort_controller:338:5)
        at EventTarget.onAbort (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/any-signal/index.js:11:16)
        at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
        at EventTarget.dispatchEvent (node:internal/event_target:677:26)
        at abortSignal (node:internal/abort_controller:308:10)
        at AbortController.abort (node:internal/abort_controller:338:5)
        at EventTarget.onAbort (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/any-signal/index.js:11:16)
        at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
        at EventTarget.dispatchEvent (node:internal/event_target:677:26)
        at abortSignal (node:internal/abort_controller:308:10)
        at TimeoutController.abort (node:internal/abort_controller:338:5)
        at TimeoutController.abort (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/timeout-abort-controller/index.js:26:18)
        at DefaultDialer.stop (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/libp2p/src/connection-manager/dialer/index.ts:135:25)
        at /home/evil_liskov/repos/dreamcatcher-stack/node_modules/libp2p/src/components.ts:140:25
        at Array.map (<anonymous>)
        at DefaultComponents.stop (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/libp2p/src/components.ts:139:59)
        at /home/evil_liskov/repos/dreamcatcher-stack/node_modules/libp2p/src/libp2p.ts:325:44
        at Array.map (<anonymous>)
        at Libp2pNode.stop (/home/evil_liskov/repos/dreamcatcher-stack/node_modules/libp2p/src/libp2p.ts:325:21)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at stopSafe (/home/evil_liskov/repos/dreamcatcher-stack/pkg/interblock/src/w305-libp2p/src/PulseNet.js:218:5)
        at PulseNet.stop (/home/evil_liskov/repos/dreamcatcher-stack/pkg/interblock/src/w305-libp2p/src/PulseNet.js:114:5)
        at Interpulse.stop (/home/evil_liskov/repos/dreamcatcher-stack/pkg/interblock/src/w310-interpulse/src/Interpulse.js:243:7)
        at async Promise.all (index 1)
        at Object.<anonymous> (/home/evil_liskov/repos/dreamcatcher-stack/pkg/interblock/src/w310-interpulse/test/mount.test.js:8:5) {
      code: 'ABORT_ERR',
      type: 'aborted'
    }
  ]
}
```

#### Steps to reproduce the error:
I don't have a good clean reproduction sorry - if you try to dial some multiaddrs and then call `.stop()` on the libp2p library, this error appears.

**Comment by achingbrain** [comment]
What version of node are you using?  [This comment](https://github.com/nodejs/node/issues/43639#issuecomment-1465043499) seems to imply it's been fixed in `14.21.3`?

Also the error message is a little confusing - it says all promises were rejected, but the errors list only has one error so `this.addrs` will have only had one entry.  If that's the case then there would be no other promises that would have resolved and caused the call to `Promise.any` to return.

I think we really need a repro case here.

**Comment by inverted-capital** [comment]
node version: v18.14.0
Yes great point about the single entry.  I don't yet have a clean repro and this is not a blocking issue.

**Comment by inverted-capital** [comment]
thank you 🙏 love the switch to a queue based model
