### ISSUE TITLE
`libp2p.contentRouting.provide(cid)` throwing TypeError

### ISSUE THREAD

**Issue by vaibhavmuchandi** [libp2p/js-libp2p#1721]
- **Version**:
0.43.4 and 0.44

- **Subsystem**:
Listener

#### Severity:
Critical

#### Description:
`libp2p.contentRouting.provide(CID(bagaaieray4wbhwyae72hzvhyqedc36bd34iq26yokl4mvi7m2fsfytwqq2vq))` throws
`TypeError: AbortSignal.timeout is not a function
    at QueryManager.run (file:///home/vaibhav/Desktop/error-libp2p/node_modules/@libp2p/kad-dht/dist/src/query/manager.js:61:42)
    at run.next (<anonymous>)
    at PeerRouting.getClosestPeers (file:///home/vaibhav/Desktop/error-libp2p/node_modules/@libp2p/kad-dht/dist/src/peer-routing/index.js:169:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/vaibhav/Desktop/error-libp2p/node_modules/it-map/dist/src/index.js:8:30
    at async file:///home/vaibhav/Desktop/error-libp2p/node_modules/it-parallel/dist/src/index.js:27:30`

#### Steps to reproduce the error:
````
const createCID = async (id) => {
  const bytes = json.encode({ id });

  const hash = await sha256.digest(bytes);
  const cid = CID.create(1, json.code, hash);
  return cid;
};

const createBootsrapNodes = async () => {
  for (let i = 0; i < 5; i++) {
    const node = await createLibp2p({
      addresses: {
        listen: ["/ip4/0.0.0.0/tcp/0/ws"],
      },
      transports: [webSockets()],
      connectionEncryption: [noise()],
      streamMuxers: [mplex()],
      pubsub: gossipsub({ allowPublishToZeroPeers: true }),
      dht: kadDHT(),
    } as any);
    bootstrappers.push(node.getMultiaddrs()[0]);
  }
};

const createNode = async () => {
  const node = await createLibp2p({
    addresses: {
      listen: ["/ip4/0.0.0.0/tcp/0/ws"],
    },
    transports: [webSockets()],
    connectionEncryption: [noise()],
    streamMuxers: [mplex()],
    pubsub: gossipsub({ allowPublishToZeroPeers: true }),
    peerDiscovery: [
      bootstrap({
        list: bootstrappers,
      }),
    ],
    dht: kadDHT(),
  } as unknown as Libp2pOptions);
  return node;
};

const main = async () => {
  const cid = await createCID(mockId);

  createBootsrapNodes();

  setTimeout(async () => {
    const node1 = await createNode();
    const node2 = await createNode();
    const node3 = await createNode();

    node1.addEventListener("peer:connect", (_evt) => {
      console.log(`Connected to ${_evt.detail.remotePeer.toString()}`);
    });

    node2.addEventListener("peer:connect", (_evt) => {
      console.log(`Connected to ${_evt.detail.remotePeer.toString()}`);
    });

    node3.addEventListener("peer:connect", (_evt) => {
      console.log(`Connected to ${_evt.detail.remotePeer.toString()}`);
    });

    await node1.dial(node2.getMultiaddrs()[0]);
    await node2.dial(node3.getMultiaddrs()[0]);

    setTimeout(async () => {
      await node3.contentRouting.provide(cid);
    }, 5000);
  }, 15000);
};
````

**Comment by vaibhavmuchandi** [comment]
Upgrading nodejs to LTS solved this
