### ISSUE TITLE
 I get this error when I create multiple subNodes , protocol selection failed

### ISSUE THREAD

**Issue by rockey2020** [libp2p/js-libp2p#1861]
- **Version**:

```
{
"dependencies": {
    "@chainsafe/libp2p-gossipsub": "^9.0.0",
    "@chainsafe/libp2p-noise": "^12.0.1",
    "@chainsafe/libp2p-yamux": "^4.0.2",
    "@libp2p/mdns": "^8.0.0",
    "@libp2p/mplex": "^8.0.4",
    "@libp2p/peer-id-factory": "^2.0.4",
    "@libp2p/tcp": "^7.0.3",
    "@libp2p/websockets": "^6.0.3",
    "@nodeutils/defaults-deep": "^1.1.0",
    "eventemitter2": "^6.4.9",
    "it-map": "^3.0.3",
    "it-pb-stream": "^4.0.1",
    "libp2p": "^0.45.9",
    "p-queue": "^7.3.4",
    "uuid": "^9.0.0"
  },
}
```

- **Platform**:

mac 13.4.1 (22F82)

- **Subsystem**:

#### Description:

```
CodeError: protocol selection failed
    at Module.select (file:///Users/berry/WebstormProjects/anynat/node_modules/@libp2p/multistream-select/dist/src/select.js:47:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionImpl.newStream [as _newStream] (file:///Users/berry/WebstormProjects/anynat/node_modules/libp2p/dist/src/upgrader.js:323:50)
    at async ConnectionImpl.newStream (file:///Users/berry/WebstormProjects/anynat/node_modules/libp2p/dist/src/connection/index.js:85:24)
    at async Libp2pNode.<anonymous> (file:///Users/berry/WebstormProjects/anynat/dist-dev/index.js:10275:20)
CodeError: protocol selection failed
    at Module.select (file:///Users/berry/WebstormProjects/anynat/node_modules/@libp2p/multistream-select/dist/src/select.js:47:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionImpl.newStream [as _newStream] (file:///Users/berry/WebstormProjects/anynat/node_modules/libp2p/dist/src/upgrader.js:323:50)
    at async ConnectionImpl.newStream (file:///Users/berry/WebstormProjects/anynat/node_modules/libp2p/dist/src/connection/index.js:85:24)
    at async Libp2pNode.<anonymous> (file:///Users/berry/WebstormProjects/anynat/dist-dev/index.js:10275:20)
CodeError: protocol selection failed
    at Module.select (file:///Users/berry/WebstormProjects/anynat/node_modules/@libp2p/multistream-select/dist/src/select.js:47:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionImpl.newStream [as _newStream] (file:///Users/berry/WebstormProjects/anynat/node_modules/libp2p/dist/src/upgrader.js:323:50)
    at async ConnectionImpl.newStream (file:///Users/berry/WebstormProjects/anynat/node_modules/libp2p/dist/src/connection/index.js:85:24)
    at async Libp2pNode.<anonymous> (file:///Users/berry/WebstormProjects/anynat/dist-dev/index.js:10275:20)
```

#### Steps to reproduce the error:

```
import { webSockets } from "@libp2p/websockets";
import { tcp } from "@libp2p/tcp";
import { yamux } from "@chainsafe/libp2p-yamux";
import { mplex } from "@libp2p/mplex";
import { noise } from "@chainsafe/libp2p-noise";
import { autoNATService } from "libp2p/autonat";
import { createLibp2p } from "libp2p";
import defaultsDeep from "@nodeutils/defaults-deep";
import { Libp2pOptions } from "libp2p/src";
import { mdns } from "@libp2p/mdns";
import { gossipsub } from "@chainsafe/libp2p-gossipsub";

export const createNode = async (options?: Libp2pOptions) => {
  const defaultConfig: Libp2pOptions = {
    transports: [webSockets(), tcp()],
    streamMuxers: [yamux(), mplex()],
    connectionEncryption: [noise()],
    services: {
      nat: autoNATService({
        timeout: 1000 * 30,
        maxInboundStreams: 1024 * 5,
        maxOutboundStreams: 1024 * 5,
      }),
      pubsub: gossipsub({ allowPublishToZeroPeers: true }),
    },
    addresses: {
      listen: [
        "/ip4/0.0.0.0/tcp/0/ws",
        "/ip6/::1/tcp/0/ws",
        "/ip4/0.0.0.0/tcp/0",
        "/ip6/::1/tcp/0",
      ],
    },
    peerDiscovery: [
      mdns({
        interval: 1000 * 30,
      }),
    ],
  };

  return createLibp2p(defaultsDeep(defaultConfig, options ?? {}));
};
```

```
import { createNode } from "../helper/createNode.ts";
import map from "it-map";
import { pipeline } from "node:stream/promises";
import { pbStream } from "it-pb-stream";

export const mainNode = async () => {
  const nodeListener = await createNode();

  await nodeListener.handle(["/chat/1.0.0"], async ({ stream }) => {
    const pb = pbStream(stream);

    // setInterval(() => {
    //   pb.write(
    //     new TextEncoder().encode(
    //       "我是mainNode:" + Math.ceil(Math.random() * 1000),
    //     ),
    //   );
    // }, 3000);

    pipeline(
      stream.source,
      (source) =>
        map(source, (buf) => new TextDecoder().decode(buf.subarray())),
      async (source) => {
        for await (const msg of source) {
          console.log("mainNode接受到信息:", msg);
        }
      },
    );
  });
};
```

```
import { createNode } from "../helper/createNode.ts";
import map from "it-map";
import { pipeline } from "node:stream/promises";
import { pbStream } from "it-pb-stream";

export const subNode = async () => {
  const nodeListener = await createNode();

  nodeListener.addEventListener("peer:discovery", async (evt) => {
    const remotePeer = evt.detail;
    const connection = await nodeListener.dial(remotePeer.id);
    const stream = await connection.newStream(["/chat/1.0.0"]);

    const pb = pbStream(stream);

    // setInterval(() => {
    //   pb.write(
    //     new TextEncoder().encode(
    //       "我是subNode:" + Math.ceil(Math.random() * 1000),
    //     ),
    //   );
    // }, 3000);

    pipeline(
      stream.source,
      (source) =>
        map(source, (buf) => new TextDecoder().decode(buf.subarray())),
      async (source) => {
        for await (const msg of source) {
          console.log("subNode接受到信息:", msg);
        }
      },
    );
  });
};
```

```
import { subNode } from "./nodes/subNode";
import { mainNode } from "./nodes/mainNode";

mainNode();
subNode();
subNode();

```

> **I get this error when I create multiple subNodes**

**Comment by rockey2020** [comment]
My mistake, in p2p is not to distinguish between master and child nodes
