### ISSUE TITLE
`libp2p.contentRouting.findProvider` fails with `more peers required`

### ISSUE THREAD

**Issue by vaibhavmuchandi** [libp2p/js-libp2p#1945]
- **Version**:
    "@libp2p/bootstrap": "^9.0.2",
    "@libp2p/crypto": "^2.0.2",
    "@libp2p/kad-dht": "^10.0.2",
    "@libp2p/mplex": "^9.0.2",
    "@libp2p/peer-id-factory": "^3.0.2",
    "@libp2p/pubsub-peer-discovery": "^8.0.4",
    "@libp2p/websockets": "^7.0.2",
    "libp2p": "^0.46.3",
    "@chainsafe/libp2p-gossipsub": "^10.0.0",
    "@chainsafe/libp2p-noise": "^13.0.0",
    "@chainsafe/libp2p-yamux": "^5.0.0",

- **Platform**:
Darwin Kernel Version 22.4.0

- **Subsystem**:
DHT

#### Severity:
High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
I have a set of pre-configured bootstraps and relay. One of the node after dialing to the bootstraps and relay uses `libp2p.contentRouting.provide(cid)`. After a while, another node uses `libp2p.contentRouting.findProvider(cid)`. 
Query fails with the error:- 

```
Node 1 connected to 12D3KooWQPECNLhhKE5mVdgeVR79eyKyUT3pdZ63GFeHAiMSo9S1
Node 1 connected to 12D3KooWKJpnqi6bqmrEPxJoSfUdC5yxB7s4DGxNanuNLmx7SVpQ
Node 1 connected to 12D3KooWJPu4cQUxnkkwhBnzmSGQYB93aUgerYNeCFgihiLEbg5w
Node 1 connected to 12D3KooWKDR1bFM6eXcwAZnWdpTNR9uhRpsFWoj9Cc8495KWy5pR
Node 2 connected to 12D3KooWQPECNLhhKE5mVdgeVR79eyKyUT3pdZ63GFeHAiMSo9S1
Node 2 connected to 12D3KooWKJpnqi6bqmrEPxJoSfUdC5yxB7s4DGxNanuNLmx7SVpQ
Node 2 connected to 12D3KooWKDR1bFM6eXcwAZnWdpTNR9uhRpsFWoj9Cc8495KWy5pR
Node 2 connected to 12D3KooWJPu4cQUxnkkwhBnzmSGQYB93aUgerYNeCFgihiLEbg5w
Node 1 connected to 12D3KooWHFcB2CEzv1Aik4avhzpZ6N8S8y7fw5NPi9c3xZodfRQZ
Node 2 connected to 12D3KooWHFcB2CEzv1Aik4avhzpZ6N8S8y7fw5NPi9c3xZodfRQZ
Node 1 announcing with address: /dns4/alpha-relay.mydomain.live/tcp/443/wss/p2p/12D3KooWHFcB2CEzv1Aik4avhzpZ6N8S8y7fw5NPi9c3xZodfRQZ/p2p-circuit/p2p/12D3KooWK7cVAkKcUqtM6tPbxHzsBCBu7EJXLgm6WFPSGBthHfn5
Node 2 announcing with address: /dns4/alpha-relay.mydomain.live/tcp/443/wss/p2p/12D3KooWHFcB2CEzv1Aik4avhzpZ6N8S8y7fw5NPi9c3xZodfRQZ/p2p-circuit/p2p/12D3KooWK7cVAkKcUqtM6tPbxHzsBCBu7EJXLgm6WFPSGBthHfn5
Providing...
Provided.
Querying...
file:///Users/vaibhav/Desktop/app/node_modules/.pnpm/libp2p@0.46.3_supports-color@9.4.0/node_modules/libp2p/dist/src/content-routing/utils.js:41
        throw new CodeError(`more peers required, seen: ${seen}  min: ${min}`, 'NOT_FOUND');
              ^

CodeError: more peers required, seen: 0  min: 1
    at requirePeers (file:///Users/vaibhav/Desktop/app/node_modules/.pnpm/libp2p@0.46.3_supports-color@9.4.0/node_modules/libp2p/dist/src/content-routing/utils.js:41:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CompoundContentRouting.findProviders (file:///Users/vaibhav/Desktop/app/node_modules/.pnpm/libp2p@0.46.3_supports-color@9.4.0/node_modules/libp2p/dist/src/content-routing/index.js:31:9)
    at async libp2pCoreTest (file:///Users/vaibhav/Desktop/app/packages/tests/dist/discovery-manual.test.js:71:20) {
  code: 'NOT_FOUND',
  props: {}
}
```

#### Steps to reproduce the error:
```
const createCID = async (id: string): Promise<CID> => {
  const bytes = json.encode({ id });
  const hash = await sha256.digest(bytes);
  const cid = CID.create(1, json.code, hash);
  return cid;
};
const delay = (duration) => {
  return new Promise<void>((resolve) => {
    setTimeout(() => {
      resolve()
    }, duration)
  })
}
const libp2pCoreTest = async () => {
  const cid = await createCID("abc")
  const createNode = async () => {
    const options = {
      addresses: {
        announce: [`/dns4/alpha-relay.mydomain.live/tcp/443/wss/p2p/12D3KooWHFcB2CEzv1Aik4avhzpZ6N8S8y7fw5NPi9c3xZodfRQZ/p2p-circuit`]
      },
      transports: [webSockets(), circuitRelayTransport({ discoverRelays: 2 })],
      connectionEncryption: [noise()],
      streamMuxers: [yamux(), mplex()],
      services: {
        pubsub: gossipsub({ allowPublishToZeroPeers: true }),
        identify: identifyService(),
        dht: kadDHT({
          // this is necessary because this node is not connected to the public network
          // it can be removed if, for example bootstrappers are configured
          allowQueryWithZeroPeers: true,
        }),
      },
      peerDiscovery: [bootstrap({ list: bootstraps }), pubsubPeerDiscovery()],
    };
    const node = await createLibp2p(options as any)
    return node
  }

  const node1 = await createNode()
  node1.addEventListener("peer:connect", (_evt) => {
    console.log(`Node 1 connected to ${_evt.detail.toString()}`)
  })
  node1.addEventListener("self:peer:update", (_evt) => {
    console.log(`Node 1 announcing with address: ${node1.getMultiaddrs().toString()}`)
  })
  const node2 = await createNode()
  node2.addEventListener("peer:connect", (_evt) => {
    console.log(`Node 2 connected to ${_evt.detail.toString()}`)
  })
  node2.addEventListener("self:peer:update", (_evt) => {
    console.log(`Node 2 announcing with address: ${node1.getMultiaddrs().toString()}`)
  })
  await delay(10000)
  console.log("Providing...")
  await node1.contentRouting.provide(cid)
  console.log("Provided.")
  await delay(10000)
  console.log("Querying...")
  const providers = await node2.contentRouting.findProviders(cid)
  for await (let provider of providers) {
    console.log(provider)
  }
}
libp2pCoreTest()
```

**Comment by maschad** [comment]
Would you be able to [provide the debug logs](https://github.com/libp2p/js-libp2p/blob/master/doc/GETTING_STARTED.md#debugging) as well prior to that error? You can do this by setting the debug flag to `libp2p:kad-dht:*`

**Comment by maschad** [comment]
Understood, If you are using websockets, bear in mind that due to browser’s security policies you cannot establish unencrypted connection from a secure context. The simplest solution is to setup SSL with nginx and proxy to the node and setup a domain name for the certificate.
