### ISSUE TITLE
Cannot npm install with Node.js 10

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#204]
The `wrtc` module does not have a prebuilt binary for version `0.1.1` (currently pinned to this specific version in package.json).

```
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.1/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:432:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/alan/Code/protocol-labs/js-libp2p/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/alan/Code/protocol-labs/js-libp2p/node_modules/wrtc
node-pre-gyp ERR! node -v v10.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.1/Release/node-v64-darwin-x64.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure
CMake binary could not be found. Please verify your PATH.
Running ncmake build
```

I installed `cmake` using `brew install cmake` and whilst `npm install` succeeded, running `npm test` failed with the following:

```
/Users/alan/Code/protocol-labs/js-libp2p/node_modules/node-cmake/index.js:40
  if(!found) throw new Error('Unable to find native module');
             ^

Error: Unable to find native module
    at requireNativeModule (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/node-cmake/index.js:40:20)
    at Object.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/wrtc/lib/binding.js:3:39)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/wrtc/lib/peerconnection.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/wrtc/lib/index.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/test/transports.node.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/test/node.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/alan/Code/protocol-labs/js-libp2p/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/alan/Code/protocol-labs/js-libp2p/node_modules/mocha/bin/_mocha:573:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

I'm on macOS 10.13.4 running Node.js 10.4.1.

**Comment by VictorBjelkholm** [comment]
Currently the CI builds for js-libp2p + Node.js 10.4.1 fails because of this:

![image](https://user-images.githubusercontent.com/459764/41910153-1c34e7e8-7949-11e8-903c-59cbd38f56ce.png)

**Comment by diasdavid** [comment]
Related:
- https://github.com/js-platform/node-webrtc/issues/255
- https://github.com/js-platform/node-webrtc/issues/256
