### ISSUE TITLE
bug: undeclared events dependency breaks vite builds

### ISSUE THREAD

**Issue by weboko** [libp2p/js-libp2p#2110]
- **Version**: 0.46.12

#### Severity:
Medium - A non-essential functionality does not work, performance issues, etc.

#### Description:
Since `connectionManager/utils` has [events dependency](https://github.com/libp2p/js-libp2p/blob/96166ada5bd7f8eeb1373e83223f63b7fe684951/packages/libp2p/src/connection-manager/utils.ts#L1) to nodejs package I assume and there is no alias or guard for the browser it creates problems for consumers that are using the lib without polyfills. 

In particular, it happens to `vite` https://vitejs.dev/ which by default does not any kinds of polyfills. 

#### Steps to reproduce the error:
Take any project with `vite` and install to it `libp2p`, try building the project and observe the problem. 
Additional context can be found in issue on our side - https://github.com/waku-org/js-waku/issues/1564

```
✓ built in 4.98s
"setMaxListeners" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/libp2p@0.46.12/node_modules/libp2p/dist/src/connection-manager/utils.js".
file: /Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/libp2p@0.46.12/node_modules/libp2p/dist/src/connection-manager/utils.js:1:9
1: import { setMaxListeners } from 'events';
            ^
2: import { logger } from '@libp2p/logger';
3: import { multiaddr } from '@multiformats/multiaddr';
[vite-plugin-sveltekit-compile] "setMaxListeners" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/libp2p@0.46.12/node_modules/libp2p/dist/src/connection-manager/utils.js".
file: /Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/libp2p@0.46.12/node_modules/libp2p/dist/src/connection-manager/utils.js:1:9
1: import { setMaxListeners } from 'events';
            ^
2: import { logger } from '@libp2p/logger';
3: import { multiaddr } from '@multiformats/multiaddr';
✓ built in 9.44s
error during build:
RollupError: "setMaxListeners" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/libp2p@0.46.12/node_modules/libp2p/dist/src/connection-manager/utils.js".
    at error (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:13604:16)
    at Module.traceVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:14029:29)
    at ModuleScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:12547:39)
    at FunctionScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at ChildScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at BlockScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at BlockScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at TrackingScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at BlockScope.findVariable (file:///Users/okozlov/Status/tmp/draft/waku-objects-playground/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by maschad** [comment]
I don't think the steps to reproduce this issue are correct given we have multiple examples that use vite with libp2p, such as [libp2p in the browser](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser/webrtc/browser-to-browser) that don't have this problem, do you have another example of this occuring independently of this issue? 

Our build tool [builds browser bundles separately](https://github.com/ipfs/aegir/blob/master/src/cmds/build.js#L17) and so I think this may be related to how the consumer is using [rollup's tree shaking](https://github.com/rollup/rollup#tree-shaking), but I can't say definitively since they are also using svelte.

**Comment by wemeetagain** [comment]
More plainly the problem is that we're using the nodejs build-in `events` package, but it isn't listed in our dependencies and its not clear how to handle that package or our usage of it in browser builds. (The answer is to hope that the consumer uses a bundler that magically resolves the `events` package)

As far as I know, the `setMaxListeners` is only used in nodejs because nodejs prints a warning if too many event listeners are registered.
It would be nicer to use a library that "works" in browsers that we use here instead of silently using the node library which requires bundler BS.

eg:

```ts
// add to `@libp2p/interface/events` ??

// noop if in browser
let setMaxListeners = (n?: number, ...eventTargets: (DOMEventTarget | EventEmitter)[]) => {}

try {
  const {setMaxListeners: s} = await import('node:events')
  setMaxListeners = s
} catch (e) {}

export {setMaxListeners}
```

then in libp2p
```ts
import {setMaxListeners} from '@libp2p/interface/events'

...

setMaxListeners(Infinity, signal)
```

**Comment by achingbrain** [comment]
I think we need to add events as a dep to the modules that use it.  It will not be imported in node since it doesn't allow overriding the names of built-in modules.

This problem doesn't occur when we build the browser bundle in the monorepo with esbuild because kad-dht declares events as a dependency so it is hoisted and as such present and resolvable in `node_modules`.

**Comment by achingbrain** [comment]
Just do `npm ls events` to see which dependency is pulling it in.

**Comment by maschad** [comment]
> > kad-dht isn't a dependency of this example, so I still believe this is a bundler issue.
> 
> Just do `npm ls events` to see which dependency is pulling it in.

It's not being pulled in

```
js-libp2p-webrtc-private-to-private@1.0.0 /Users/horizon/Desktop/work/vite-project
└── (empty)
```

**Comment by achingbrain** [comment]
With vite I see a warning in the browser console:

```
browser-external:events:9 Module "events" has been externalized for browser compatibility. Cannot access "events.setMaxListeners" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

so I think they're doing a more gentle version of webpack 5's [rug-pull](https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed).
