### ISSUE TITLE
Getting Started tuto error at ipfs_video_streaming/libp2p_getting/client.js:31:56

### ISSUE THREAD

**Issue by scenaristeur** [libp2p/js-libp2p#2125]
i've just started the getting started tuto but i've got this message 

```
DEBUG="libp2p:*" node client.js
  libp2p:transports adding transport @libp2p/websockets +0ms
  libp2p:connection-manager started +0ms
  libp2p:bootstrap Starting bootstrap node discovery, discovering peers after 1000 ms +0ms
  libp2p:transports no addresses were provided for listening, this node is dial only +13ms
  libp2p:connection-manager:auto-dial not enough connections 0/50 - will dial peers to increase the number of connections +0ms
  libp2p:connection-manager:auto-dial selected 0/0 peers to dial +3ms
Discovered QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
Discovered QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
  libp2p:connection-manager:auto-dial not enough connections 0/50 - will dial peers to increase the number of connections +1s
  libp2p:connection-manager:auto-dial selected 2/2 peers to dial +3ms
  libp2p:connection-manager:auto-dial connecting to a peerStore stored peer QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN +0ms
  libp2p:connection-manager dial QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN +1s
  libp2p:connection-manager:auto-dial connecting to a peerStore stored peer QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +1ms
  libp2p:connection-manager dial QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +1ms
  libp2p:connection-manager:dial-queue loading multiaddrs for QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN +0ms
  libp2p:connection-manager:dial-queue loading multiaddrs for QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +0ms
  libp2p:connection-manager:dial-queue loaded multiaddrs for QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN [
  '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN'
] +1ms
  libp2p:connection-manager:dial-queue loaded multiaddrs for QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb [
  '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb'
] +2ms
  libp2p:connection-manager:utils resolved /dnsaddr/sv15.bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN to [
  '/ip6/2604:1380:45e3:6e00::1/tcp/4001/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip6/2604:1380:45e3:6e00::1/udp/4001/quic-v1/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/dns6/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip4/139.178.91.71/tcp/4001/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/dns4/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip6/2604:1380:45e3:6e00::1/udp/4001/quic/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip4/139.178.91.71/udp/4001/quic-v1/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip4/139.178.91.71/udp/4001/quic/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN'
] +0ms
  libp2p:connection-manager:utils resolved /dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN to [
  '/ip6/2604:1380:45e3:6e00::1/tcp/4001/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip6/2604:1380:45e3:6e00::1/udp/4001/quic-v1/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/dns6/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip4/139.178.91.71/tcp/4001/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/dns4/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip6/2604:1380:45e3:6e00::1/udp/4001/quic/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip4/139.178.91.71/udp/4001/quic-v1/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/ip4/139.178.91.71/udp/4001/quic/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN'
] +0ms
  libp2p:connection-manager:dial-queue creating dial target for [
  '/dns6/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
  '/dns4/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN'
] +11ms
  libp2p:websockets dialing /dns6/sv15.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN +0ms
  libp2p:websockets dialing sv15.bootstrap.libp2p.io:443 +1ms
  libp2p:connection-manager:utils resolved /dnsaddr/am6.bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb to [
  '/ip4/147.75.87.27/tcp/4001/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip6/2604:1380:4602:5c00::3/udp/4001/quic/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip6/2604:1380:4602:5c00::3/tcp/4001/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip4/147.75.87.27/udp/4001/quic-v1/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip4/147.75.87.27/udp/4001/quic/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip6/2604:1380:4602:5c00::3/udp/4001/quic-v1/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb'
] +32ms
  libp2p:connection-manager:utils resolved /dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb to [
  '/ip4/147.75.87.27/tcp/4001/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip6/2604:1380:4602:5c00::3/udp/4001/quic/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip6/2604:1380:4602:5c00::3/tcp/4001/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip4/147.75.87.27/udp/4001/quic-v1/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip4/147.75.87.27/udp/4001/quic/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/ip6/2604:1380:4602:5c00::3/udp/4001/quic-v1/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb'
] +0ms
  libp2p:connection-manager:dial-queue creating dial target for [
  '/dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb'
] +29ms
  libp2p:websockets dialing /dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +28ms
  libp2p:websockets dialing am6.bootstrap.libp2p.io:443 +0ms
  libp2p:websockets connected /dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +207ms
  libp2p:websockets new outbound connection /dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +0ms
  libp2p:upgrader Starting the outbound connection upgrade +0ms
  libp2p:upgrader selecting outbound crypto protocol [ '/noise' ] +0ms
  libp2p:upgrader encrypting outbound connection to QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb +77ms
  libp2p:upgrader outbound selecting muxer [ '/yamux/1.0.0', '/mplex/6.7.0' ] +100ms
  libp2p:upgrader /yamux/1.0.0 selected as muxer protocol +47ms
  libp2p:upgrader Successfully upgraded outbound connection +0ms
  libp2p:connection-manager:connection-pruner checking max connections limit 1/300 +0ms
  libp2p:websockets outbound connection /dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb upgraded +230ms
  libp2p:connection-manager:dial-queue dial to /dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb aborted +439ms
  libp2p:connection-manager:dial-queue dial to /dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb succeeded +0ms
  libp2p:connection-manager:dial-queue:error error dialling AbortError: The task was aborted.
    at file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/p-queue/dist/index.js:109:31
    at PQueue._PQueue_tryToStartAnother (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/p-queue/dist/index.js:285:13)
    at PQueue._PQueue_next (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/p-queue/dist/index.js:237:85)
    at file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/p-queue/dist/index.js:131:88
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) +0ms
node:internal/event_target:1033
  process.nextTick(() => { throw err; });
                           ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at Libp2pNode.<anonymous> (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/client.js:31:56)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at Libp2pNode.dispatchEvent (node:internal/event_target:692:26)
    at Libp2pNode.dispatchEvent (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/@libp2p/interface/dist/src/events.js:40:30)
    at Libp2pNode.events.dispatchEvent (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/libp2p/dist/src/libp2p.js:49:41)
    at EventEmitter.safeDispatchEvent (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/@libp2p/interface/dist/src/events.js:50:21)
    at DefaultConnectionManager._onConnect (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/libp2p/dist/src/connection-manager/index.js:262:25)
    at DefaultConnectionManager.onConnect (file:///home/smag/dev/ipfs_video_streaming/libp2p_getting/node_modules/libp2p/dist/src/connection-manager/index.js:231:19)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at EventEmitter.dispatchEvent (node:internal/event_target:692:26)

Node.js v18.18.0

```

with just this basic code 

```
import { createLibp2p } from 'libp2p'
import { webSockets } from '@libp2p/websockets'
import { noise } from '@chainsafe/libp2p-noise'
import { mplex } from '@libp2p/mplex'
import { yamux } from '@chainsafe/libp2p-yamux'

import { bootstrap } from '@libp2p/bootstrap'

// Known peers addresses
const bootstrapMultiaddrs = [
  '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
  '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN'
]

const node = await createLibp2p({
  transports: [webSockets()],
  connectionEncryption: [noise()],
  streamMuxers: [yamux(), mplex()],
  peerDiscovery: [
    bootstrap({
      list: bootstrapMultiaddrs, // provide array of multiaddrs
    })
  ]
})

node.addEventListener('peer:discovery', (evt) => {
  console.log('Discovered %s', evt.detail.id.toString()) // Log discovered peer
})

node.addEventListener('peer:connect', (evt) => {
  console.log('Connected to %s', evt.detail.remotePeer.toString()) // Log connected peer
})
```

**Comment by dozyio** [comment]
The `peer:connect` event  returns `connection.remotePeer` (see https://github.com/libp2p/js-libp2p/blob/main/packages/libp2p/src/connection-manager/index.ts#L462), so there isn't a `remotePeer` property thus you get the `Cannot read properties of undefined (reading 'toString')` error - you can do something like this though

```js
node.addEventListener('peer:connect', (evt) => {
  console.log('Connected to %s', evt.detail.toString()) // Log connected peer
})
```

**Comment by achingbrain** [comment]
You can also check the documentation for the [different types of event emitted by libp2p](https://libp2p.github.io/js-libp2p/interfaces/_libp2p_interface.Libp2pEvents.html#peer_connect) including full types for the passed events.

Closing as this seems to be user error.  Please re-open if you find a problem in libp2p.
