### ISSUE TITLE
webrtc/browser-to-browser error  Rollup failed to resolve import "@libp2p/webrtc" 

### ISSUE THREAD

**Issue by scenaristeur** [libp2p/js-libp2p#2126]
trying browser-to-browser example, i've got this error message 

```
npm i && npm run build

added 197 packages, and audited 199 packages in 37s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> js-libp2p-webrtc-private-to-private@1.0.0 build
> vite build

vite v4.4.10 building for production...
✓ 3 modules transformed.
✓ built in 72ms
[vite]: Rollup failed to resolve import "@libp2p/webrtc" from "/home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@libp2p/webrtc" from "/home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/vite/dist/node/chunks/dep-3bba9c7e.js:48215:27)
    at onRollupWarning (file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/vite/dist/node/chunks/dep-3bba9c7e.js:48247:9)
    at onwarn (file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/vite/dist/node/chunks/dep-3bba9c7e.js:47975:13)
    at file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///home/smag/dev/ipfs_video_streaming/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser/node_modules/rollup/dist/es/shared/node-entry.js:24822:26

```

**Comment by maschad** [comment]
This looks like it could be a bundler configuration issue, the examples are [tested on ci](https://github.com/libp2p/js-libp2p/actions/runs/6470743466/job/17567798500?pr=2133) so we should be able to detect if they are broken, could you include the other environment details such as the platform and version in the [PR issue template](https://github.com/libp2p/js-libp2p/blob/master/.github/ISSUE_TEMPLATE/open_an_issue.md) ? Have you made any changes to the [package.json](https://github.com/libp2p/js-libp2p/blob/master/examples/libp2p-in-the-browser/webrtc/browser-to-browser/package.json)?

**Comment by scenaristeur** [comment]
Linux mint 21
