### ISSUE TITLE
Failing "TCP + WebSockets + WebRTCStar" tests

### ISSUE THREAD

**Issue by lgierth** [libp2p/js-libp2p#227]
- **Version**: libp2p/js-libp2p@7f68a1343392f10c37a50b9afed2ef677c250653
- **Platform**: Linux swift 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: transports

#### Steps to reproduce the error:

```
> node -v
v8.11.3
> npm -v
5.6.0
> npm run test:node
[...]
  62 passing (1m)
  2 pending
  2 failing

  1) transports
       TCP + WebSockets + WebRTCStar
         nodeAll.dial nodeWebRTCStar using PeerInfo:
     Uncaught AssertionError: expected [Error: Circuit not enabled and all transports failed to dial peer QmZnhDJws3Ufp4Aqj5jS3EYTGWoFBEKS6HgFNgGfn1FtoN!] to not exist
      at nodeAll.dial (test/transports.node.js:515:28)
      at Dialer._switch.dial [as callback] (src/index.js:294:27)
      at waterfall (node_modules/libp2p-switch/src/dial.js:110:12)
      at node_modules/async/internal/once.js:12:16
      at next (node_modules/async/waterfall.js:21:29)
      at node_modules/async/internal/onlyOnce.js:12:16
      at waterfall (node_modules/libp2p-switch/src/dial.js:160:7)
      at node_modules/async/internal/once.js:12:16
      at next (node_modules/async/waterfall.js:21:29)
      at node_modules/async/internal/onlyOnce.js:12:16
      at waterfall (node_modules/libp2p-switch/src/dial.js:202:16)
      at node_modules/async/internal/once.js:12:16
      at next (node_modules/async/waterfall.js:21:29)
      at node_modules/async/internal/onlyOnce.js:12:16
      at nextTransport (node_modules/libp2p-switch/src/dial.js:365:18)
      at switch.transport.dial (node_modules/libp2p-switch/src/dial.js:382:18)
      at dialer.dialMany (node_modules/libp2p-switch/src/transport.js:69:16)
      at f (node_modules/once/once.js:25:25)
      at map (node_modules/libp2p-switch/src/limit-dialer/index.js:61:14)
      at node_modules/async/internal/map.js:32:9
      at node_modules/async/internal/once.js:12:16
      at iteratorCallback (node_modules/async/eachOf.js:60:13)
      at node_modules/async/internal/onlyOnce.js:12:16
      at Object.callback (node_modules/async/internal/map.js:29:13)
      at node_modules/async/internal/queue.js:101:31
      at node_modules/async/internal/onlyOnce.js:12:16
      at _dialWithTimeout (node_modules/libp2p-switch/src/limit-dialer/queue.js:44:16)
      at Timeout.timeoutCallback [as _onTimeout] (node_modules/async/timeout.js:74:13)

  2) transports
       TCP + WebSockets + WebRTCStar
         nodeAll.hangUp nodeWebRTCStar using PeerInfo:

      Uncaught AssertionError: expected [ Array(2) ] to have a length of 3 but got 2
      + expected - actual

      -2
      +3
      
      at forEach (test/transports.node.js:473:61)
      at Array.forEach (<anonymous>)
      at check (test/transports.node.js:472:28)
      at Timeout.setTimeout [as _onTimeout] (test/transports.node.js:524:26)



Command failed: mocha --timeout 5000 --ui bdd --colors --exit test/node.js test/**/*.spec.js
null
null
Error: Command failed: mocha --timeout 5000 --ui bdd --colors --exit test/node.js test/**/*.spec.js
null
null
    at makeError (/home/user/workspace/js-libp2p/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/user/workspace/js-libp2p/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libp2p@0.22.0 test:node: `aegir test -t node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libp2p@0.22.0 test:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-25T02_53_07_435Z-debug.log

```

**Comment by diasdavid** [comment]
All good now :) @vasco-santos can you log here what was the issue?
