### ISSUE TITLE
Node Crashes In crypto.js When Dialed 

### ISSUE THREAD

**Issue by threejeez** [libp2p/js-libp2p#229]
- **Version**: 0.23.0
- **Platform**: Linux ip-172-31-90-222 4.14.33-51.37.amzn1.x86_64 #1 SMP Thu May 3 20:07:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: SECIO

#### Description: 

I am running a very basic bootstrap node on EC2 and only when I give it a peerId (instead of letting it generate it's own) it crashes when dialed in crypto.js. This does not happen when I run the same test locally. 

What may be different about running a node on EC2 that would cause this to happen?

My bootstrap node bundle:

```
class MyBundle extends libp2p {
  constructor (_options) {

    const defaults = {
      modules: {
        transport: [new WebSockets(), new TCP()],
        streamMuxer: [Mplex],
        connEncryption: [SECIO]
      }     
    }

    super(defaultsDeep(_options, defaults))
  }
}
```

Creating the node:

```
function createNode (callback) {
  let node
  const id = 'QmcdGp9P2ZvahuoxgJP8yPHXn7CtDhbEpxCctyAqJiPZhf'

  waterfall([
    (cb) => PeerInfo.create({id}, cb),
    (peerInfo, cb) => {
      const peerId = peerInfo.id.toB58String()

      peerInfo.multiaddrs.add(`/ip4/0.0.0.0/tcp/4001/ipfs/${peerId}`)

      node = new MyBundle({peerInfo})

      console.log(`Starting node ${peerId}`)
      node.start(cb)
    }
  ], (err) => callback(err, node))
}
```

This is the stack trace:

```
  libp2p:tcp:listen new connection /ip4/18.212.189.186/tcp/47038 +11s
  mss:listener	 (101ck5) adding handler: /mplex/6.7.0 +0ms
  mss:listener	 (101ck5) adding handler: /spdy/3.1.0 +0ms
  mss:listener	 (101ck5) adding handler: /ipfs/id/1.0.0 +0ms
  mss:listener	 (101ck5) adding handler: /secio/1.0.0 +0ms
  mss:listener	 (101ck5) adding handler: /ipfs/ping/1.0.0 +0ms
  mss:listener	 (101ck5) adding handler: /ipfs/kad/1.0.0 +0ms
  mss:listener	 (101ck5) listener handle conn +1ms
  mss:listener	 (101ck5) writing multicodec: /multistream/1.0.0 +0ms
  libp2p:tcp:listen new connection /ip4/18.212.189.186/tcp/47040 +7ms
  mss:listener	 (11zzr4) adding handler: /mplex/6.7.0 +0ms
  mss:listener	 (11zzr4) adding handler: /spdy/3.1.0 +0ms
  mss:listener	 (11zzr4) adding handler: /ipfs/id/1.0.0 +1ms
  mss:listener	 (11zzr4) adding handler: /secio/1.0.0 +0ms
  mss:listener	 (11zzr4) adding handler: /ipfs/ping/1.0.0 +0ms
  mss:listener	 (11zzr4) adding handler: /ipfs/kad/1.0.0 +0ms
  mss:listener	 (11zzr4) listener handle conn +0ms
  mss:listener	 (11zzr4) writing multicodec: /multistream/1.0.0 +0ms
  mss:listener	 (101ck5) received ack: /multistream/1.0.0 +6ms
  mss:listener	 (11zzr4) received ack: /multistream/1.0.0 +2ms
  mss:listener	 (11zzr4) received: +1ms
  mss:listener	 (11zzr4) send ack back of: /secio/1.0.0 +0ms
  libp2p:switch:protocol-muxer registering handler with protocol /secio/1.0.0 +0ms
  libp2p:secio 1. propose - start +0ms
  libp2p:secio 1. propose - writing proposal +0ms
/home/ec2-user/bootstrap-node/node_modules/libp2p-secio/src/handshake/crypto.js:22
    pubkey: state.key.local.public.bytes,
                            ^

TypeError: Cannot read property 'public' of null
    at Object.exports.createProposal (/home/ec2-user/bootstrap-node/node_modules/libp2p-secio/src/handshake/crypto.js:22:29)
    at propose (/home/ec2-user/bootstrap-node/node_modules/libp2p-secio/src/handshake/propose.js:18:31)
    at series (/home/ec2-user/bootstrap-node/node_modules/libp2p-secio/src/handshake/index.js:13:13)
    at /home/ec2-user/bootstrap-node/node_modules/async/internal/parallel.js:31:39
    at replenish (/home/ec2-user/bootstrap-node/node_modules/async/internal/eachOfLimit.js:66:17)
    at /home/ec2-user/bootstrap-node/node_modules/async/internal/eachOfLimit.js:71:9
    at eachOfLimit (/home/ec2-user/bootstrap-node/node_modules/async/eachOfLimit.js:39:36)
    at /home/ec2-user/bootstrap-node/node_modules/async/internal/doLimit.js:9:16
    at _parallel (/home/ec2-user/bootstrap-node/node_modules/async/internal/parallel.js:30:5)
    at series (/home/ec2-user/bootstrap-node/node_modules/async/series.js:83:26)
```

#### Steps to reproduce the error:

Run a node on EC2 host and dial it from another node.

**Comment by jacobheun** [comment]
The reason SECIO is failing is that the PeerId is being created without any public or private keys, you're just giving it an id string. Not sure why this is working locally for you without looking more into your setup; if you created that id string on your machine it's possible there is some keychain storing going on there, but I'm not positive.

If you're trying to replicate the re-creation of a specific node you may want to look at passing an actual peerId instance to the PeerInfo setup and doing so with a secured private key, [`PeerId.createFromPrivKey`](https://github.com/libp2p/js-peer-id#createfromprivkeyprivkey), so that you have all of the crypto information you need for SECIO handshakes.

**Comment by threejeez** [comment]
Thanks. Yeah, it could be some Mac magic that makes it work locally?

I tried generating an RSA keypair via `ssh-keygen -t rsa` and supply the private key to `PeerId.createFromPrivKey` and get the following exception at [line 89 in libp2p-crypto/src/keys/index.js](https://github.com/libp2p/js-libp2p-crypto/blob/master/src/keys/index.js#L89):

```Error: Unknown wire type: 7
    at skip (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/protons/src/compile/decode.js:198:13)
    at Object.decode (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/protons/src/compile/decode.js:156:18)
    at Object.exports.unmarshalPrivateKey (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/libp2p-crypto/src/keys/index.js:87:34)
    at waterfall (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/peer-id/src/index.js:221:25)
    at nextTask (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/async/waterfall.js:16:14)
    at exports.default (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/async/waterfall.js:26:5)
    at Function.exports.createFromPrivKey (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/peer-id/src/index.js:220:3)
    at waterfall (/Users/gregg/Development/automation-protocol/bootstrap-node/main.js:108:14)
    at nextTask (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/async/waterfall.js:16:14)
    at exports.default (/Users/gregg/Development/automation-protocol/bootstrap-node/node_modules/async/waterfall.js:26:5)```

**Comment by threejeez** [comment]
I tried regenerating the key in the same way and am now getting the following error: `Groups are not supported`. Am I generating the key improperly??

**Comment by jacobheun** [comment]
So, it looks like `createFromPrivKey` is actually expecting a ProtoBuf so it errors when it's just getting a key. I've got a working snippet using a private key, it would be nice if this was added into peer-id so it could be created from the private key buffer without needing to externally use `libp2p-crypto`.

```js
const PeerId = require('peer-id')
const crypto = require('libp2p-crypto')

const privateKeyBuffer = Buffer.from(`your private key`)

crypto.keys.import(privateKeyBuffer), null /*null or your private keys password*/, (err, privateKey) => {
  if (err) return console.log(err)
  PeerId.createFromPrivKey(crypto.keys.marshalPrivateKey(privateKey, 'rsa'), (err, peerId) => {
    if (err) return console.log(err)
    console.log(peerId.toJSON())
  })
})
```

**Comment by jacobheun** [comment]
I created https://github.com/libp2p/js-peer-id/issues/82 to hopefully get this improved. If you're interested in submitting a PR for it, that would be great!

**Comment by threejeez** [comment]
Awesome! Will take a look at it... perhaps I'll throw my hat in the ring 🎩😁
Thanks again for your help!
