### ISSUE TITLE
dht: kadDHT() causes TypeError: Cannot destructure property 'kBucketSize' of 'init' as it is undefined

### ISSUE THREAD

**Issue by alexeyvolkoff** [libp2p/js-libp2p#2381]
- **Version**:
```
"dependencies": {
    "@chainsafe/libp2p-gossipsub": "^11.1.0",
    "@libp2p/bootstrap": "^10.0.13",
    "@libp2p/kad-dht": "^12.0.5",
    "@libp2p/mdns": "^10.0.13",
    "@libp2p/tcp": "^9.0.13",
    "@libp2p/webrtc": "^4.0.17",
    "@libp2p/websockets": "^8.0.13",
    "@orbitdb/core": "^2.0.1",
    "blockstore-level": "^1.1.7",
    "helia": "^4.0.0",
    "i": "^0.3.7",
    "interface-blockstore": "^5.2.9",
    "libp2p": "^1.2.1",
    "npm": "^10.4.0"
```

- **Platform**:
node 20.11.0
ubuntu 22.04

- **Subsystem**:
kad-dht

#### Description:
Adding dht to libp2p configuration causes crash:
 
```
         services: {
            identify: identify(),
            pubsub: gossipsub({ allowPublishToZeroPeers: true }),
            dht: kadDHT()
        }
```

```
TypeError: Cannot destructure property 'kBucketSize' of 'init' as it is undefined.
    at new KadDHT (file:///home/alexey/projects/orbit/node_modules/@libp2p/kad-dht/dist/src/kad-dht.js:109:17)
    at file:///home/alexey/projects/orbit/node_modules/@libp2p/kad-dht/dist/src/index.js:115:28
    at new Libp2pNode (file:///home/alexey/projects/orbit/node_modules/libp2p/dist/src/libp2p.js:126:33)
    at createLibp2pNode (file:///home/alexey/projects/orbit/node_modules/libp2p/dist/src/libp2p.js:321:12)
    at async createLibp2p (file:///home/alexey/projects/orbit/node_modules/libp2p/dist/src/index.js:44:18)
    at async main (file:///home/alexey/projects/orbit/index.js:56:20)
```

#### Steps to reproduce the error:
Just define dht: kadDHT() in services{}

**Comment by achingbrain** [comment]
I think this could use a more helpful error message, but as of [v12.x.x](https://github.com/libp2p/js-libp2p/releases/tag/kad-dht-v12.0.0) you need to configure the `KadDHT` module to tell it about your DHT configuration.

For example, [how to connect to the public Amino/IPFS DHT](https://www.npmjs.com/package/@libp2p/kad-dht#example---connecting-to-the-ipfs-amino-dht), or [how to connect to a local, LAN-only DHT](https://www.npmjs.com/package/@libp2p/kad-dht#example---connecting-to-a-lan-only-dht).

**Comment by abuvanth** [comment]
dht: kadDHT({
        kBucketSize: 20,
      }),

should fix issue
