### ISSUE TITLE
Unhandled error: ERR_SDP_HANDSHAKE_ABORTED

### ISSUE THREAD

**Issue by christroutner** [libp2p/js-libp2p#2386]
- **Version**:
1.2.1

- **Platform**:
Linux optiplex-f 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
webRTC

#### Severity:
- Critical - System crash, application panic.

#### Description:
I'm running libp2p in a node.js environment. An unhandled error is frequently thrown that crashes the application. 

Here is the error message:

```
file:///home/trout/work/ipfs-file-pin-service/node_modules/@libp2p/webrtc/dist/src/private-to-private/initiate-connection.js:44
            connectedPromise.reject(new CodeError('SDP handshake aborted', 'ERR_SDP_HANDSHAKE_ABORTED'));
                                    ^

CodeError: SDP handshake aborted
    at AbortSignal.sdpAbortedListener (file:///home/trout/work/ipfs-file-pin-service/node_modules/@libp2p/webrtc/dist/src/private-to-private/initiate-connection.js:44:37)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
    at abortSignal (node:internal/abort_controller:292:10)
    at AbortController.abort (node:internal/abort_controller:323:5)
    at AbortSignal.onAbort (file:///home/trout/work/ipfs-file-pin-service/node_modules/any-signal/dist/src/index.js:8:20)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
    at abortSignal (node:internal/abort_controller:292:10)
    at Timeout._onTimeout (node:internal/abort_controller:112:7)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ERR_SDP_HANDSHAKE_ABORTED',
  props: {}
}

```

#### Steps to reproduce the error:
The error often happens shortly after startup, but it's inconsistent so I don't have a description of how to reliably reproduce it. It seems to depend on the order of connection attempts, which is random in my application.

**Comment by achingbrain** [comment]
What version of the transport are you using?  I ask because there's no string matching 'ERR_SDP_HANDSHAKE_ABORTED' in the codebase currently, but there was [this PR](https://github.com/libp2p/js-libp2p/pull/2299) that fixed a bug with very similar symptoms to those you are reporting.

**Comment by christroutner** [comment]
I was using @libp2p/webrtc v3.2.11. I've upgraded to v4.0.17 and everything seems fine so far. I'll reopen this issue if I see the error again.
