### ISSUE TITLE
dns4 dialling fails

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#260]
Just wondering if I'm doing something wrong:

```js
await ipfs.api.swarm.connect('/dns4/localhost/tcp/40020/ipfs/QmUCxqJEyKZ2dC8fLL6vKXZTW7RihxgfnS8NTqNHxsaJuw')
```

Results in:

```
Error: Circuit not enabled and all transports failed to dial peer QmUCxqJEyKZ2dC8fLL6vKXZTW7RihxgfnS8NTqNHxsaJuw!
    at nextTransport (/path/to/project/node_modules/libp2p-switch/src/dial.js:365:27)
    at switch.transport.dial (/path/to/project/node_modules/libp2p-switch/src/dial.js:382:18)
    at dialer.dialMany (/path/to/project/node_modules/libp2p-switch/src/transport.js:69:16)
    at f (/path/to/project/node_modules/once/once.js:25:25)
    at map (/path/to/project/node_modules/libp2p-switch/src/limit-dialer/index.js:61:14)
    at /path/to/project/node_modules/async/internal/map.js:32:9
    at /path/to/project/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/path/to/project/node_modules/async/eachOf.js:60:13)
    at /path/to/project/node_modules/async/internal/onlyOnce.js:12:16
    at Object.callback (/path/to/project/node_modules/async/internal/map.js:29:13)
    at /path/to/project/node_modules/async/internal/queue.js:101:31
    at /path/to/project/node_modules/async/internal/onlyOnce.js:12:16
    at _dialWithTimeout (/path/to/project/node_modules/libp2p-switch/src/limit-dialer/queue.js:44:16)
    at /path/to/project/node_modules/async/timeout.js:79:26
    at Socket.transport.dial (/path/to/project/node_modules/libp2p-switch/src/limit-dialer/queue.js:81:18)
    at Socket.f (/path/to/project/node_modules/once/once.js:25:25)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This is with a `js-ipfs` daemon - running the same thing with a `go-ipfs` daemon works as expected.

**Comment by jacobheun** [comment]
There was an update to mafmt and libp2p-tcp recently to add support for tcp over dns. If you update to `libp2p-tcp@0.13.0` that should resolve the issue.  I'll close this for now, but feel free to open if that doesn't solve the problem.
