### ISSUE TITLE
WebRTCTransport.dial AbortError

### ISSUE THREAD

**Issue by christroutner** [libp2p/js-libp2p#2702]
- **Version**:
- libp2p v1.9.1

- **Platform**:
- Linux hp-elitedesk01 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
- WebRTC

#### Severity:
- Critical - System crash, application panic.

#### Description:
I had filed [this previous issue](https://github.com/libp2p/js-libp2p/issues/2670) about issues I was having with the @libp2p/webrtc package. That was resolved and the current [package versions can be seen here](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/4fc54aa9c587634f1a0374e03510f719ca8c999c/package.json) and the [code for initializing libp2p can be found here](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/4fc54aa9c587634f1a0374e03510f719ca8c999c/src/adapters/ipfs/ipfs.js#L129-L227).

I'm now encountering what appears to be a race condition inside the webRTC libraries. The node will run for a while and then randomly will crash with the following error message:

```
file:///home/safeuser/ipfs-service-provider/node_modules/race-signal/dist/src/index.js:22
        return Promise.reject(new AbortError(opts?.errorMessage, opts?.errorCode, opts?.errorName));
                              ^


AbortError: The operation was aborted
    at raceSignal (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/race-signal/dist/src/index.js:22:31)
    at YamuxStream.closeWrite (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/@libp2p/utils/dist/src/abstract-stream.js:230:19)
    at YamuxStream.close (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/@libp2p/utils/dist/src/abstract-stream.js:189:18)
    at file:///home/safeuser/ipfs-bch-wallet-service/node_modules/libp2p/dist/src/connection/index.js:118:63
    at Array.map (<anonymous>)
    at ConnectionImpl.close (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/libp2p/dist/src/connection/index.js:118:44)
    at initiateConnection (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/@libp2p/webrtc/dist/src/private-to-private/initiate-connection.js:146:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebRTCTransport.dial (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/@libp2p/webrtc/dist/src/private-to-private/transport.js:93:65)
    at async DefaultTransportManager.dial (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/libp2p/dist/src/transport-manager.js:87:20)
    at async queue.add.peerId.peerId [as fn] (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/libp2p/dist/src/connection-manager/dial-queue.js:168:38)
    at async raceSignal (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/race-signal/dist/src/index.js:28:16)
    at async Job.run (file:///home/safeuser/ipfs-bch-wallet-service/node_modules/@libp2p/utils/dist/src/queue/job.js:55:28) {
  type: 'aborted',
  code: 'ABORT_ERR'
}

Node.js v20.17.0
```

#### Steps to reproduce the error:
The error does not occur right away. It will appear at some point within 30 minutes while the node is running. It forces the app to crash and the process manager will restart it. But then the crash will happen again within 30 minutes.

**Comment by christroutner** [comment]
This might be the same issue I reported in #2462. I'll take a closer look by replacing my `node_modules` and `package-lock.json` files and report back here.

However, I don't think that this is the same, as I'm building the application into a docker container with the `--no-cache` flag. It should be installing the `node_modules` folder from scratch. ..but the `package-lock.json` file would be copied from the repository. So maybe that is the issue.

I'll report back on my findings.

**Comment by christroutner** [comment]
I carefully deleted my `node_modules` folder and `package-lock.json` file before installing dependencies and I'm still getting the above error. As far as I can see it does not have anything to do with an unclean install as was claimed in #2462.

**Comment by Chomtana** [comment]
I'm experiencing the same issue when trying to connect with peers from different countries. It seems unable to establish a connection via WebRTC, even with TURN servers added to the list.

**Comment by Chomtana** [comment]
TURN works for regular internet connections across countries without this error, but it doesn't function properly with restrictive VPNs. This error indicates that WebRTC has failed to establish a connection with the peer.

**Comment by christroutner** [comment]
I wouldn't mind if webRTC fails to connect, but this error causes the application to crash and exit, and there doesn't seem to be any way to wrap it with try/catch to handle the exception.

**Comment by cristianmadularu** [comment]
This is happening for us as well causing our Node processes to crash.

**Comment by cristianmadularu** [comment]
> I wouldn't mind if webRTC fails to connect, but this error causes the application to crash and exit, and there doesn't seem to be any way to wrap it with try/catch to handle the exception.

<img width="485" alt="image" src="https://github.com/user-attachments/assets/dc014c67-2661-4d65-bfdd-130f249e7676">

@christroutner while this is not a 'solution' (more of a temporary workaround), you might consider an application level handler and consider not allowing the application to crash if an AbortException throws...
Risky approach since there is no guarantee that the app is still in a good state... but... an ugly workaround nevertheless....

**Comment by christroutner** [comment]
I appreciate the tip @cristianmadularu.

I ended up just disabling WebRTC in my application until this issue can be resolved. It would be great to have, but it's not a core requirement.

**Comment by silkroadnomad** [comment]
@christroutner if I remove WebRTC on NodeJS from transports, is circuit-relay and autonat, dcutr for browsers to connect peer-to-peer (via WebRTC) to each other still possible when coming both via wss or webtransport?

**Comment by christroutner** [comment]
My understanding is that if you remove WebRTC, then circuit-relay is not possible. I don't know about the rest of your question.

**Comment by achingbrain** [comment]
Browsers can listen on circuit relay addresses where the relayed connection is established over WebSockets, but any incoming connections will be time/data limited so it's only useful under certain conditions.

For two browsers to upgrade to an unlimited direct connection you need WebRTC.

**Comment by achingbrain** [comment]
> *Steps to reproduce the error:*
>
> The error does not occur right away. It will appear at some point within 30 minutes while the node is running. It forces the app to crash and the process manager will restart it. But then the crash will happen again within 30 minutes.

@christroutner I've been running the `ipfs-service-provider` all day and haven't seen a single crash.

The deps were quite out of date so that might have something to do with it.  I've [opened a PR](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/pull/168 that updates them.

I will open a followup with my changes that re-add WebRTC support.

**Comment by achingbrain** [comment]
Here is the followup that re-enables WebRTC - https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/pull/169

**Comment by christroutner** [comment]
This is just the prod I needed. Thanks @achingbrain. I've been intending to update this thread the last few days.

I updated ipfs-service-provider to use helia v5.2.0, libp2p v2.6.2, and @libp2p/webrtc v5.1.0. The WebRTC and Circuit Relay stuff is working **much** better.

However, I'm still seeing the random AbortError. Sometimes it happens right after startup, sometimes it doesn't happen for hours. It seems completely random.

I have however managed to catch it by adding this code snippet to the first JS file to get executed:

```javascript
process.on('unhandledRejection', (reason, promise) => {
  console.log(`Handling ${reason.code} error`)
})
```

That at least prevents it from crashing the entire app. I still can't seem to find the root cause, but it seems to be the same issue.

I'll update the code to print out the error and I'll try to add it to this thread, to see if the error stack has changed at all.

In the meantime, I'll review your PR and compare it to the changes I've already made.

**Comment by christroutner** [comment]
After [updating all npm dependencies](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/9fa5eafe9518a2a8bb0242fa326422fc9022cb5f/package.json), I'm still seeing the AbortError randomly. Here is the stack from the latest error:

```
Handling ABORT_ERR error. stack:  AbortError: The operation was aborted
    at raceSignal (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/race-signal/dist/src/index.js:22:31)
    at YamuxStream.closeWrite (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/@libp2p/utils/dist/src/abstract-stream.js:231:19)
    at YamuxStream.close (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/@libp2p/utils/dist/src/abstract-stream.js:190:18)
    at stream.close (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/@libp2p/utils/dist/src/stream-to-ma-conn.js:15:15)
    at ConnectionImpl.close [as _close] (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/libp2p/dist/src/upgrader.js:426:30)
    at async ConnectionImpl.close (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/libp2p/dist/src/connection/index.js:118:13)
    at async initiateConnection (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/@libp2p/webrtc/dist/src/private-to-private/initiate-connection.js:148:17)
    at async WebRTCTransport.dial (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/@libp2p/webrtc/dist/src/private-to-private/transport.js:92:65)
    at async queue.add.peerId.peerId [as fn] (file:///home/trout/work/psf/code/ipfs-service-provider/node_modules/libp2p/dist/src/connection-manager/dial-queue.js:173:38) {
  type: 'aborted',
  code: 'ABORT_ERR'
}
```

**Comment by christroutner** [comment]
> Do you know what the multiaddr is that your node is trying to dial? That might help me narrow it down a bit.

No, not at the time the error occurs.

At a high level, when a new node is trying to connect to the network, it listens on an 'announcement' pubsub channel. When a new node announces itself that it hasn't seen, the announcement object contains multiaddrs. The node will go down the list of multiaddrs and try to connect to each multiaddr until it's successful or reaches the end of the list.

Also, a timer will kick off every few minutes to try and connect to nodes it knows about and hasn't been able to connect to.

So the stage is set for a race condition. Everything is jumbled in production.

If the error was thrown within the code path, it would be caught. I would know exactly where in the code path the error happened and exactly which node and which transport it was using. But because this is manifesting as an AbortError that I have to catch in a general way, I can't isolate exactly what is causing the error. And there is no info in the stack to help me isolate the code path within my own app.

**Comment by achingbrain** [comment]
Ok, I think I've figured out what's happening.

1. A new connection to a WebRTC address is initiated
2. The dialing peer dials the relay and opens a new connection (e.g. one did not exist before)
3. Doing the SDP handhsake times out and the abort signal fires its "abort" event and is now aborted
4. The dialing peer gives up and [closes the connection](https://github.com/libp2p/js-libp2p/blob/main/packages/transport-webrtc/src/private-to-private/initiate-connection.ts#L203-L205)
5. The stream muxer [closes all streams](https://github.com/ChainSafe/js-libp2p-yamux/blob/master/src/muxer.ts#L307-L309) on the connection
6. Each stream [races](https://github.com/libp2p/js-libp2p/blob/main/packages/utils/src/abstract-stream.ts#L296-L300) closing the read and write ends of the stream against the (aborted) signal
7. race-signal notices the signal is aborted and immediately [returns a rejection](https://github.com/achingbrain/race-signal/blob/main/src/index.ts#L42)
8. The `.closeWrite` method rejects due also using the (aborted) signal
9. The promise that the muxer is racing against the (aborted) signal has nothing `await`ing it and so 💥 

This should be fixed by https://github.com/achingbrain/race-signal/pull/64 released in `race-signal@1.1.2`
