### ISSUE TITLE
Ping Service Error: UnexpectedEOFError - Unexpected End of Input

### ISSUE THREAD

**Issue by fastalks** [libp2p/js-libp2p#2770]
- **Version**:

"libp2p": "^2.1.9",

- **Platform**:

64-bit (Windows) , Mac mini (Apple M1)
- **Subsystem**:

"@libp2p/ping": "^2.0.8",
#### Description:

- What you did
 I set up node1 on Windows and node2 on Mac. They discovered each other via mDNS and established a connection. I then added ping services and set the environment variable DEBUG=libp2p:*
- What happened
I encountered an UnexpectedEOFError: unexpected end of input. Sometimes, the connection disconnects permanently.

#### Steps to reproduce the error:

```
const libp2p = await createLibp2p({
    start: false,
    addresses: {
      listen: [
        '/ip4/0.0.0.0/tcp/0',
        '/ip4/0.0.0.0/tcp/0/ws',
        '/webrtc']
    },
    transports: [
      tcp(),
      webSockets({
        // this allows non-secure WebSocket connections for purposes of the demo
        filter: filters.all
      }),
      // support dialing/listening on WebRTC addresses
      webRTC(),
      circuitRelayTransport({
        discoverRelays: 1
      }) //
    ],
    streamMuxers: [
      yamux()
    ],
    connectionEncrypters: [
      noise()
    ],
    connectionManager: {
      maxConnections: 100
    },
    peerDiscovery: [
      mdns({
        interval: 20e3
      }),
    ],
    connectionGater: {
      denyDialMultiaddr: () => {
        // by default we refuse to dial local addresses from browsers since they
        // are usually sent by remote peers broadcasting undialable multiaddrs and
        // cause errors to appear in the console but in this example we are
        // explicitly connecting to a local node so allow all addresses
        return false
      }
    },
    services:{
      identify: identify(),
      ping: ping(),
      pubsub: gossipsub(),
    },
  });

```
```
[1]   libp2p:ping incoming ping from 12D3KooWFztNbYJ3eLNHomLtMyFgVb4ZGSLaTYTsCCJ2yiZPFFa9 complete in 109ms +109ms
[1]   libp2p:connection:outbound:2jjjmb1728963020005 incoming stream opened on /ipfs/ping/1.0.0 +10s
[1]   libp2p:ping incoming ping from 12D3KooWFztNbYJ3eLNHomLtMyFgVb4ZGSLaTYTsCCJ2yiZPFFa9 +10s
[1]   libp2p:ping:error incoming ping from 12D3KooWFztNbYJ3eLNHomLtMyFgVb4ZGSLaTYTsCCJ2yiZPFFa9 failed with error UnexpectedEOFError: unexpected end of input
[1]     at Object.read (E:\electron-workspace\electron-react-remotecontrol-app\.erb\dll\main.bundle.dev.js:115723:31)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async E:\electron-workspace\electron-react-remotecontrol-app\.erb\dll\main.bundle.dev.js:91174:29 {
[1]   code: 'ERR_UNEXPECTED_EOF'
[1] } +10s
[1]   libp2p:yamux:inbound:94 abort with error UnexpectedEOFError: unexpected end of input
[1]     at Object.read (E:\electron-workspace\electron-react-remotecontrol-app\.erb\dll\main.bundle.dev.js:115723:31)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async E:\electron-workspace\electron-react-remotecontrol-app\.erb\dll\main.bundle.dev.js:91174:29 {
[1]   code: 'ERR_UNEXPECTED_EOF'
[1] } +0ms
[1]   libp2p:yamux:inbound:94 try to send reset to remote +0ms
[1]   libp2p:ping incoming ping from 12D3KooWFztNbYJ3eLNHomLtMyFgVb4ZGSLaTYTsCCJ2yiZPFFa9 complete in 26ms +26ms
```

**Comment by justin0mcateer** [comment]
The while(true) loop here:
https://github.com/libp2p/js-libp2p/blame/main/packages/protocol-ping/src/ping.ts#L62

seems to have no way to exit successfully. It will read 32 byte chunks until it can't read anymore.

This doesn't seem to cause any practical problem, but it generates a few error logs every time the ping runs.

**Comment by cristianmadularu** [comment]
We are running into the exact same issue. Any update on it? Our logs generate a lot of 'errors' entries and it is not clear if they are real issues or not.
Thanks

**Comment by justin0mcateer** [comment]
@achingbrain Thanks so much for working on this!
