### ISSUE TITLE
Dialling a peer and subscribing to a pubsub topic but "subscription-change" event does not always fire

### ISSUE THREAD

**Issue by haydenyoung** [libp2p/js-libp2p#2771]
- **Version**:
2.1.9

- **Platform**:
Linux 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
Pubsub (GossipSub)

#### Severity:
Medium

#### Description:
OrbitDB has two peers connecting to one another and sharing messages using Libp2p and custom protocols. To initiate the message exchange, OrbitDB relies on the event subscription-change by attaching a listener to it. When fired, the listener will dial a protocol from peerA from peerB and initiate an exchange of data via streams.

When bootstrapping peerA's address in peerB, subscription-change fires reliably. However, when a discovery mechanism is used (we have been using mdns for local network discovery) and the peerB dials peerA manually, subscription-change becomes unreliable, sometimes firing, sometimes not.

Watching the [pipePeerReadStream function in GossipSub](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/d9e4374b568be6eb490cadc924f42576ed6cfea4/src/index.ts#L1036), it appears that  the [stream doesn't contain anything and the data handling is completely skipped](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/d9e4374b568be6eb490cadc924f42576ed6cfea4/src/index.ts#L1039), giving the appearance that the event doesn't fire when, in fact, it does but it skips over much of the function because there is no data to read.

#### Steps to reproduce the error:

Prerequisites:

```
git clone https://github.com/orbitdb/orbit-db-pinner.git
cd orbit-db-pinner
git checkout pinner/new-refactor-2-helia-upgrade
npm i
```

To see a successful test run:

In terminal 1 start the relay:
```
npm run start:relay
```

In terminal 2 start the first pinner server:
```
npm run start:orbiter1
```
In terminal 3 start the second pinner server:
```
npm run start:orbiter2
```

In terminal 4, run the unit tests:
```
npm run test
```
or
```
npm run test:ci
```

All tests should run successfully.

To see subscription-change fail:

Kill Orbiter1 and Orbiter2

In src/lib/libp2p-config.js, uncomment [this line](https://github.com/orbitdb/orbit-db-pinner/blob/0c8959849bf2f18058afaff0c1010bacd4b762d7/src/utils/libp2p-config.js#L7) and [this line](https://github.com/orbitdb/orbit-db-pinner/blob/0c8959849bf2f18058afaff0c1010bacd4b762d7/src/utils/libp2p-config.js#L35) to enable local network discovery. [Comment out the node bootstrapping](https://github.com/orbitdb/orbit-db-pinner/blob/0c8959849bf2f18058afaff0c1010bacd4b762d7/src/utils/libp2p-config.js#L32). Config should now look like:

```
    peerDiscovery: [
      /*
      bootstrap({
        list: ['/ip4/127.0.0.1/tcp/54321/p2p/16Uiu2HAmBzKcgCfpJ4j4wJSLkKLbCVvnNBWPnhexrnJWJf1fDu5y']
      }),
      */
      mdns()
    ],
```

In [src/daemon.js](https://github.com/orbitdb/orbit-db-pinner/blob/pinner/new-refactor-2-helia-upgrade/src/daemon.js#L55), add the following [after line 55](https://github.com/orbitdb/orbit-db-pinner/blob/0c8959849bf2f18058afaff0c1010bacd4b762d7/src/daemon.js#L55):

```
  libp2p.addEventListener('peer:discovery', async (event) => {
    const { id: peerId, multiaddrs } = event.detail
      
    if (peerId !== libp2p.peerId) {
      console.log("dialling", peerId.toString())
      await libp2p.peerStore.save(peerId, { multiaddrs })
      await libp2p.dial(peerId)
      console.log("dialled", peerId.toString())
    }
  })
```

In terminal 1 start the relay:
```
npm run start:relay
```

In terminal 2 start the first pinner server:
```
npm run start:orbiter1
```
In terminal 3 start the second pinner server:
```
npm run start:orbiter2
```

In terminal 4, run the unit tests:
```
npm run test
```
or
```
npm run test:ci
```

The dialling will ensure all relevant peers are connected in a similar fashion to when bootstrapping on initialization; Orbiter1, Orbiter2, Lander1, Lander2. However, subscription-change will fail which will result in timeout errors such as:

```
Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/orbitdb/voyager/test/e2e-browser.test.js)
```

The assumption would be that whether bootstrapped or dialled manually, the subscription-change event would fire regardless.

**Comment by NiKrause** [comment]
i have been trying to replicate the issue:
1. the above repo and branch does not exist anymore - it is now called voyager but the test scenario seems executable.
2. when I run the tests - everything seems ok until host 2 crashes with an older symptom https://github.com/libp2p/js-libp2p/issues/3063 which I don't remember at the moment what was the reason for it. 

I guess some library needs to be updated:
```
  voyager:daemon listening on /ip4/192.168.64.1/tcp/55442/ws/p2p/12D3KooWExPZDJ4JsVpEBYbFm1ucmDVZn1GzF7uxULQbZkCUBbPK +0ms
  voyager:host start voyager +0ms
  voyager:host default access: allow all +1ms
  voyager:host open replicated databases +83ms
  voyager:host 0 databases opened +4ms
Voyager started
  voyager:host handle request 1 3045022100dfd3bee9519a021ae00bda6bbad8c44a1e3f85aefa66dab0597281f7d614a56d02203ee977e3d40e95d46091e3d895d8577bff1290c566b24d93c5428f07fefa122e zdpuAwm29yTzwgESSFregEfJMBiw45cXCCyvgCFDLETek5gmA [ '/orbitdb/zdpuAvHG9Akwx78s31cYcsmCWTPecVAtVRumvAi5fUm8svP8T' ] +2m
file:///Users/nandi/libp2p-issue-2771-test/orbit-db-pinner/node_modules/it-queueless-pushable/dist/src/index.js:99
            throw new Error('Cannot push value onto an ended pushable');
                  ^

Error: Cannot push value onto an ended pushable
    at QueuelessPushable._push (file:///Users/nandi/libp2p-issue-2771-test/orbit-db-pinner/node_modules/it-queueless-pushable/dist/src/index.js:99:19)
    at QueuelessPushable.push (file:///Users/nandi/libp2p-issue-2771-test/orbit-db-pinner/node_modules/it-queueless-pushable/dist/src/index.js:86:20)
    at duplex.sink (file:///Users/nandi/libp2p-issue-2771-test/orbit-db-pinner/node_modules/it-byte-stream/dist/src/index.js:54:25)
    at async handleMessages (file:///Users/nandi/libp2p-issue-2771-test/orbit-db-pinner/src/lib/host.js:26:5)

```

**Comment by NiKrause** [comment]
Related: 
https://github.com/libp2p/js-libp2p/issues/3063
https://github.com/libp2p/js-libp2p/issues/2321

**Comment by tabcat** [comment]
Fixed in 16.0.4
