### ISSUE TITLE
Socket hang up when disconnecting one peer connected to another

### ISSUE THREAD

**Issue by hubertokf** [libp2p/js-libp2p#340]
- **Version**:
```
"libp2p": "^0.24.4",
        "libp2p-bootstrap": "^0.9.7",
        "libp2p-kad-dht": "^0.14.9",
        "libp2p-mdns": "^0.12.2",
        "libp2p-mplex": "^0.8.5",
        "libp2p-multiplex": "^0.5.1",
        "libp2p-railing": "^0.9.2",
        "libp2p-rpc": "^0.1.1",
        "libp2p-secio": "^0.11.1",
        "libp2p-spdy": "^0.13.2",
        "libp2p-tcp": "^0.13.0",
        "libp2p-webrtc-star": "^0.15.8",
        "libp2p-websockets": "^0.12.2",
```
- **Platform**: Linux core-VirtualBox 4.18.0-16-generic #17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: -

#### Description: 
Running two instances to discovery each other, when one is closed, the other crashes with error "socket hang up". Events like peer:disconnect does not get fired.

```
/home/core/code/node_modules/pull-stream/sinks/drain.js:22
                throw end
                ^

Error: socket hang up
    at Stream.onclose (/home/core/code/node_modules/spdy-transport/lib/spdy-transport/connection.js:181:15)
    at Object.onceWrapper (events.js:277:13)
    at Stream.emit (events.js:194:15)
    at Stream.s.destroy (/home/core/code/node_modules/pull-stream-to-stream/index.js:146:7)
    at Stream.conn.on (/home/core/code/node_modules/libp2p-rpc/node_modules/libp2p-spdy/src/index.js:18:10)
    at Stream.emit (events.js:194:15)
    at next (/home/core/code/node_modules/pull-stream-to-stream/index.js:118:41)
    at /home/core/code/node_modules/pull-reader/index.js:110:13
    at /home/core/code/node_modules/pull-reader/index.js:110:13
    at /home/core/code/node_modules/pull-reader/index.js:110:13
```

#### Steps to reproduce the error: 
Here are my simple code:

```
const fs = require('fs')
const path = require('path')
const PeerInfo = require('peer-info')
const protobuf = require('protobufjs')
const ip = require('ip');


const Node = require('libp2p-rpc')

// Find this list at: https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/config-nodejs.json
const bootstrapers = [
    '/ip4/10.0.1.10/tcp/46459/ipfs/QmPnoe2fpg4zfPqPZM4Jq6PTYS63PcXdYpSYfwjEjdcsch'
]

const config = {
    name: 'your-protocol-name',
    version: '1.0.0',
    bootstrapers: [],
    multicastDNS: {
        interval: 1000   
    }
}

PeerInfo.create((err, peerInfo) => {
    if (err) throw new Error(err)
    
    protobuf.load(path.join(__dirname, './protocol.proto')).then((root) => {
        const node = new Node(peerInfo, root, config)
        var addr = '/ip4/'+ip.address()+'/tcp/46459/ipfs/'+peerInfo.id._idB58String
        
        console.log("id: ", peerInfo.id._idB58String)
        console.log("ipfs addr: ", addr)
        
        node.on('peer:connection', (conn, peer, type) => {
            console.log("peer:connection id: ", peer.id._idB58String)
            console.log(peer._connectedMultiaddr)
    
            peer.rpc.sayHello({name: 'Foo'}, (response, peer) => {
                console.log('sayHello Response', response)
            })
        })

        node.on('stop', () => {
            console.log('peer:stop')
        })

        node.on('peer:disconnect', (peer) => {
            console.log('peer:disconnect')
        })

        node.on('peer:disconnection', (peer) => {
            console.log('peer:disconnection')
        })

        node.on('error', (err) => {
            console.log('peer:error', err)
        })
        
        node.handle('sayHello', (message, peer, response) => {
            console.log('sayHello Request', message)
            response({ message: 'heyThere' })
        })
        
        node.start().then(console.log, console.error) 
    }, console.error)
})
```

**Comment by jacobheun** [comment]
Can you do an `npm ls libp2p`? It looks like you are using `libp2p-rpc` which is leveraging an older version of libp2p. Even though you're including newer versions in your dependencies list, `libp2p-rpc` is likely still using the older versions.

**Comment by hubertokf** [comment]
```
core@core-VirtualBox:~/code$ npm ls libp2p
libp2p-exehda@0.1.1 /home/core/code
├── libp2p@0.24.4 
└─┬ libp2p-rpc@0.1.1
  └── libp2p@0.12.4 
```

Yes, I'm using libp2p-rpc, maybe should I modify something. Do you have a guess of how to fix that? Actually libp2p-rpc has only one file which is a libp2p node constructor.

**Comment by jacobheun** [comment]
Yeah, 0.12 is quite old and the usage, including the constructor, has changed quite a bit since then. Since it's relatively small it would probably be easiest to just copy and refactor that code into your project.

**Comment by hubertokf** [comment]
Thanks! I'll try to refractor, then make a pull request.

Thanks for your time!

**Comment by jacobheun** [comment]
You're welcome. Closing this, if you have further issues feel free to reach out.
