### ISSUE TITLE
[circuit-relay] ipfs/interop: MAC invalid

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#420]
Occasionally when running the github.com/ipfs/interop tests, an error will occur `Error: MAC Invalid`. The error is likely coming from SECIO, https://github.com/libp2p/js-libp2p-secio/blob/v0.11.1/src/etm.js#L57, via the unbox stream. Initial thought is that this may be due to an issue with receiving a message from the relay or destination peer when we expected it from the other. Our streams may be getting crossed somewhere.

```log
  1) circuit
       js-go-go
         reconnect:
     Error: MAC Invalid: f0c8d18a25fbfc73e33ed062daa4fddfb7afb8dc39df2f93ebdf139b3c42e9b9 != 9c668e0365260562e08c685e9016aa36b1829bc1553f677d5c5baa6feb2ae615
      at parseError (node_modules/ipfs-http-client/src/utils/send-request.js:17:17)
      at ClientRequest.<anonymous> (node_modules/ipfs-http-client/src/utils/send-request.js:47:14)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at Socket.socketOnData (_http_client.js:442:20)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Related https://github.com/libp2p/js-libp2p/issues/310

**Comment by jacobheun** [comment]
Duplicate of https://github.com/libp2p/js-libp2p/issues/310
