### ISSUE TITLE
[circuit-relay] Callback was already called

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#421]
To reproduce, start JS IPFS daemon with circuit relay enabled. Wait...(might be long), eventually:

```console
$ jsipfs daemon
Initializing IPFS daemon...
Swarm listening on /p2p-circuit/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /p2p-circuit/ip4/0.0.0.0/tcp/4002/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /p2p-circuit/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /ip4/192.168.1.86/tcp/4002/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmYsRYcrQAftGS5U6XRsHdxiVDdGowAfCCYZLgxgL5JGpu
API listening on /ip4/127.0.0.1/tcp/5002
Gateway (read only) listening on /ip4/127.0.0.1/tcp/9090
Web UI available at http://127.0.0.1:5002/webui
Daemon is ready
/Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/onlyOnce.js:9:32
    at pull.collect (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-circuit/src/circuit/stream-handler.js:91:9)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/sinks/reduce.js:10:5
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/sinks/drain.js:20:24
    at read (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-length-prefixed/src/encode.js:27:25)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/sources/values.js:19:7
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-length-prefixed/src/encode.js:25:5
    at next (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/sinks/drain.js:37:9)
    at pull (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/pull.js:41:14)
```

**Comment by wemeetagain** [comment]
Circult relay implementation has completely changed since this issue
