### ISSUE TITLE
[switch] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#435]
```js
/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-switch/src/observer.js:41
    peerInfo.then((_peerInfo) => {
             ^

RangeError: Maximum call stack size exceeded
    at Promise.then (<anonymous>)
    at willObserve (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-switch/src/observer.js:41:14)
    at pull.map (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-switch/src/observer.js:34:9)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/throughs/map.js:13:23
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-reader/index.js:114:13
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-reader/index.js:114:13
    at onNext (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-catch/index.js:17:17)
    at drain (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/stream-to-pull-stream/index.js:141:18)
    at Channel.<anonymous> (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/stream-to-pull-stream/index.js:150:5)
    at Channel.emit (events.js:182:13)
```

**Comment by tobowers** [comment]
I'm seeing this too, but don't have any helpful info except that it happens for me after lots of bitswap... stack traces aren't helpful.

**Comment by wemeetagain** [comment]
The code has been reimplemented since this issue, closing as stale
