### ISSUE TITLE
UnhandledPromiseRejectionWarning while running examples

### ISSUE THREAD

**Issue by chinesebug** [libp2p/js-libp2p#458]
- **Version**: node version: v10.16.3
- **Platform**: Mac OS
- **Subsystem**:

#### Description: 
Hi, I'm new to this and while I was following this example (https://github.com/libp2p/js-libp2p/tree/master/examples/transports), I ran into UnhandledPromiseRejectionWarning. didn't find anything through google search. is it due to my node version? 
```
(node:42647) UnhandledPromiseRejectionWarning: TypeError: Expected String
    at decodeUnsafe (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/base-x/src/index.js:63:45)
    at Object.decode (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/base-x/src/index.js:110:18)
    at Object.fromB58String (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/multihashes/src/index.js:68:27)
    at Function.exports.createFromJSON (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/peer-info/node_modules/peer-id/src/index.js:216:15)
    at Function.PeerInfo.create (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/peer-info/src/index.js:48:27)
    at waterfall (/Users/MattMachine/numpy-exam/video_server/libp2p_example/1.js:30:22)
    at nextTask (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/async/waterfall.js:90:46)
    at waterfall (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/async/waterfall.js:101:5)
    at awaitable(waterfall) (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/async/internal/awaitify.js:13:28)
    at createNode (/Users/MattMachine/numpy-exam/video_server/libp2p_example/1.js:29:3)
(node:42647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:42647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:42647) UnhandledPromiseRejectionWarning: TypeError: Expected String
    at decodeUnsafe (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/base-x/src/index.js:63:45)
    at Object.decode (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/base-x/src/index.js:110:18)
    at Object.fromB58String (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/multihashes/src/index.js:68:27)
    at Function.exports.createFromJSON (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/peer-info/node_modules/peer-id/src/index.js:216:15)
    at Function.PeerInfo.create (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/peer-info/src/index.js:48:27)
    at waterfall (/Users/MattMachine/numpy-exam/video_server/libp2p_example/1.js:30:22)
    at nextTask (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/async/waterfall.js:90:46)
    at waterfall (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/async/waterfall.js:101:5)
    at awaitable(waterfall) (/Users/MattMachine/numpy-exam/video_server/libp2p_example/node_modules/async/internal/awaitify.js:13:28)
    at createNode (/Users/MattMachine/numpy-exam/video_server/libp2p_example/1.js:29:3)
(node:42647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by jacobheun** [comment]
This should not longer be an issue as of 0.27.0
