### ISSUE TITLE
Broken connection on mplex version exchange

### ISSUE THREAD

**Issue by DieMyst** [libp2p/js-libp2p#531]
- **libp2p 0.26.2, libp2p-switch 0.43.0**:
- **Ubuntu 18.04.3 LTS**:
- **npm 6.12.1**:

#### Description:
I'm trying to establish a connection between js and rust implementation of libp2p. A simple project with only TCP and mplex modules was created to reach this goal.

```
modules: {
              transport: [TCP], // TODO: try udp? try websocket?
              streamMuxer: [Mplex],
              connEncryption: []
          }
```

The connection becomes broken after nodes try to exchange with mplex version info. Log example below.

<details>
  <summary>Logs with an error</summary>

```
libp2p:tcp:dial Connecting to 30000 127.0.0.1 +17ms
  libp2p:switch:dialer:queue work:success +1ms
  libp2p:switch:dialer dialMany:success +1ms
  libp2p:conn:out:QmbX6ieh successfully dialed QmTESkr2vWDCKqiHVsyvf4iRQCBgvNDqBJ6P3yTTDb6haw +2ms
  mss:dialer     (eie2wg) dialer handle conn +0ms
  mss:dialer     (eie2wg) writing multicodec: /multistream/1.0.0 +0ms
  mss:dialer     (eie2wg) received ack: /multistream/1.0.0 +1ms
  mss:dialer     (eie2wg) handshake success +0ms
  libp2p:conn:out:QmbX6ieh selecting crypto /plaintext/1.0.0 to QmTESkr2vWDCKqiHVsyvf4iRQCBgvNDqBJ6P3yTTDb6haw +1ms
  mss:dialer     (eie2wg) dialer select /plaintext/1.0.0 +0ms
  mss:dialer     (eie2wg) writing multicodec: /plaintext/1.0.0 +0ms
  mss:dialer     (eie2wg) received ack: /plaintext/1.0.0 +1ms
  libp2p:conn:out:QmbX6ieh successfully encrypted connection to QmTESkr2vWDCKqiHVsyvf4iRQCBgvNDqBJ6P3yTTDb6haw +1ms
  libp2p:conn:out:QmbX6ieh upgrading connection to QmTESkr2vWDCKqiHVsyvf4iRQCBgvNDqBJ6P3yTTDb6haw +0ms
  mss:dialer     (flqdzk) dialer handle conn +0ms
  mss:dialer     (flqdzk) writing multicodec: /multistream/1.0.0 +0ms
  mss:dialer     (flqdzk) received ack: /multistream/1.0.0 +1ms
  mss:dialer     (flqdzk) handshake success +0ms
  libp2p:conn:out:QmbX6ieh selecting /mplex/6.7.0 +1ms
  mss:dialer     (flqdzk) dialer select /mplex/6.7.0 +0ms
  mss:dialer     (flqdzk) writing multicodec: /mplex/6.7.0 +0ms
  libp2p:conn:out:QmbX6ieh Error upgrading connection: Error: stream ended with:0 but wanted:1
    at drain (/home/diemust/git/arqada/js/node_modules/pull-reader/index.js:43:26)
    at /home/diemust/git/arqada/js/node_modules/pull-reader/index.js:63:18
    at /home/diemust/git/arqada/js/node_modules/pull-reader/index.js:20:7
    at /home/diemust/git/arqada/js/node_modules/pull-reader/index.js:114:13
    at /home/diemust/git/arqada/js/node_modules/pull-stream/throughs/map.js:19:9
    at /home/diemust/git/arqada/js/node_modules/pull-reader/index.js:114:13
    at /home/diemust/git/arqada/js/node_modules/pull-reader/index.js:114:13
    at /home/diemust/git/arqada/js/node_modules/pull-stream/throughs/map.js:19:9
    at drain (/home/diemust/git/arqada/js/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/diemust/git/arqada/js/node_modules/stream-to-pull-stream/index.js:143:5) +1ms
  libp2p:conn:out:QmbX6ieh unmuxed connection opened to QmTESkr2vWDCKqiHVsyvf4iRQCBgvNDqBJ6P3yTTDb6haw +0ms
```
</details>

#### Steps to reproduce the error:
https://github.com/DieMyst/js-rust-libp2p

Rust needs to be installed.

1) Run rust server
`make rust`
2) Run js 
`make js`

Thanks!

**Comment by jacobheun** [comment]
I believe this is related to https://github.com/libp2p/rust-libp2p/issues/1241. We fixed how js was implementing mss to support https://github.com/multiformats/multistream-select/pull/20. This should be fixed in js-libp2p > 0.27. 

Feel free to reopen if you're still having issues with newer js-libp2p versions
