### ISSUE TITLE
Already piped when connecting to go-ipfs node

### ISSUE THREAD

**Issue by ridenaio** [libp2p/js-libp2p#534]
- **Version**: 0.26.2
- **Platform**: windows x64

#### Description:

I want to establish connect to my go-ipfs node from js-ipfs using **private ipfs network** and **custom protocol**.

On the one side I use `go-ipfs v0.4.22` as a library and register new protocol as `ipfsHost.SetStreamHandler("/my/protocol/1.0.0", streamHandler)`

On the another side I use `js-ipfs v0.40.0` and call `libp2p.dialProtocol`

```
async function start() {
  const node = await IPFS.create({
    libp2p: {
      modules: {
        connProtector: new Protector(
          Buffer.from(
           '/key/swarm/psk/1.0.0/\n/base16/\n9ad6f9bbbbbb2a7308ad8793xxxxxxa974b550cc029ce41aaaaaa0c46db2f530'
          )
        )
      },
      config: {
        dht: {
          enabled: true
        },
        pubsub: {
          enabled: false
        }
      }
    }
  });

  try {
    await node.libp2p.dialProtocol(
      '/ip4/127.0.0.1/tcp/55055/ipfs/QmdnFa1Uw48ScocAZNZhv9n1Q2sGyuFMZEVjqo2eY7EuGf',
      '/my/protocol/1.0.0'
    );
  } catch (e) {
    console.log(e);
  }
}
```

My code fails with this error

```
Error: already piped
    at sink (D:\projects\test-app\node_modules\ipfs\node_modules\pull-pair\index.js:11:13)
    at consume (D:\projects\test-app\node_modules\ipfs\node_modules\pull-defer\sink.js:7:17)
    at consume (D:\projects\test-app\node_modules\ipfs\node_modules\pull-defer\sink.js:7:17)
    at Connection.consume (D:\projects\test-app\node_modules\ipfs\node_modules\pull-defer\sink.js:7:17)
    at pull (D:\projects\test-app\node_modules\ipfs\node_modules\pull-stream\pull.js:43:9)
    at Dialer.handle (D:\projects\test-app\node_modules\ipfs\node_modules\multistream-select\src\dialer\index.js:52:7)
    at ClassIsWrapper._protocolHandshake (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\connection\index.js:464:14)
    at ClassIsWrapper.shake (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\connection\index.js:183:10)
    at createConnectionWithProtocol (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\dialer\queue.js:44:14)
    at ClassIsWrapper.connectionFSM.once (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\dialer\queue.js:270:7)
```

What am i doing wrong?

I also created issue in [js-ipfs repo](https://github.com/ipfs/js-ipfs/issues/2720)

**Comment by vasco-santos** [comment]
This code has been totally refactored with `libp2p@0.28` and this should be fixed. I am closing this, but feel free to open if this is still a problem when you updated
