### ISSUE TITLE
[docs.libp2p.io] Getting started - Js tutorial is broken

### ISSUE THREAD

**Issue by kawmaiparis** [libp2p/js-libp2p#557]
Version: node version: v12.14.1
Platform: Ubuntu 19.10

Type: Question
Severity: Low

Description:
Following the Getting started tutorial on the official Libp2p website, I am stuck with this error when I run "node src/index.js" for the first time.

(node:14122) UnhandledPromiseRejectionWarning: TypeError: Expected String
    at decodeUnsafe (/home/paris/DeFi/hello-libp2p/node_modules/base-x/src/index.js:63:45)
    at Object.decode (/home/paris/DeFi/hello-libp2p/node_modules/base-x/src/index.js:110:18)
    at Object.fromB58String (/home/paris/DeFi/hello-libp2p/node_modules/multihashes/src/index.js:68:27)
    at Function.exports.createFromJSON (/home/paris/DeFi/hello-libp2p/node_modules/peer-id/src/index.js:265:17)
    at Function.PeerInfo.create (/home/paris/DeFi/hello-libp2p/node_modules/peer-info/src/index.js:48:27)
    at createPeer (/home/paris/DeFi/hello-libp2p/src/index.js:7:14)
    at Object.<anonymous> (/home/paris/DeFi/hello-libp2p/src/index.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
(node:14122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jacobheun** [comment]
We are in the process of updating the libp2p examples on the libp2p docs site to match the current version of js-libp2p. In the interim I would recommend checking out the getting started guide in this repo, https://github.com/libp2p/js-libp2p/blob/master/doc/GETTING_STARTED.md. 

Please let us know if you have any issues with the local guide, and we'll update here when the docs site has been fixed.

cc @vasco-santos

**Comment by vasco-santos** [comment]
Hello @kawmaiparis 

Thanks for reaching out! As @jacobheun mentioned we are currently working on some post release stuff, including the website. Meanwhile, look at this repo's gueting started guide.

FYI, I created a PR yesterday to add a notice to this issue on the website [libp2p/docs#77](https://github.com/libp2p/docs/pull/77) and I intend to update the tutorial content soon

**Comment by vasco-santos** [comment]
Closing this as [libp2p/docs#78](https://github.com/libp2p/docs/pull/78) was merged! 🎉
