### ISSUE TITLE
 TypeError peerId.toB58String is not a function

### ISSUE THREAD

**Issue by VandeurenGlenn** [libp2p/js-libp2p#599]
Occurred after upgrading to js-ipfs 0.40.2

Error
```sh
TypeError: peerId.toB58String is not a function
    at Metrics.onPeerDisconnected (/home/ion/core/node_modules/libp2p/src/metrics/index.js:113:29)
    at Upgrader.onConnectionEnd (/home/ion/core/node_modules/libp2p/src/index.js:81:40)
    at Object.set (/home/ion/core/node_modules/libp2p/src/upgrader.js:269:16)
    at WebSocket.<anonymous> (/home/ion/core/node_modules/libp2p-websockets/src/socket-to-conn.js:71:29)
    at Object.onceWrapper (events.js:300:26)
    at WebSocket.emit (events.js:215:7)
    at WebSocket.emitClose (/home/ion/core/node_modules/it-ws/node_modules/ws/lib/websocket.js:194:10)
    at Socket.socketOnClose (/home/ion/core/node_modules/it-ws/node_modules/ws/lib/websocket.js:862:15)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:658:12)
```

Guilty code
https://github.com/libp2p/js-libp2p/blob/da83721d6d5ba1aad0eed5aff32b20696467746b/src/metrics/index.js#L112

platform: any
version: 0.27.2? (js-ipfs@0.41.2)

I didn't look into it, so I don't know what peerId stands for (in the code), could it be this needs to be updated?
Because all cids are strings now?

**Comment by jacobheun** [comment]
Does this occur frequently or are you able to replicate it reliably?

#601 isn't the right fix for this. `onPeerDisconnected` should be receiving a valid [`PeerId`](https://github.com/libp2p/js-peer-id) instance, which has the `toB58String` method. For some reason, it does not. My assumption, since metrics are enabled, is that the bug may be in the peer proxy code used in the upgrader for early metrics collection on connections when we don't know the peer yet.

**Comment by VandeurenGlenn** [comment]
@jacobheun It occurs every time a node disconnect's, when on #601 everything seem's fine.

''#601 isn't the right fix for this''
I figured later on this day, since peers are identified by base32 externally (if I understand correctly),
I'l try checking out the proxy code and see what I get.

Also, are Metrics enabled only when listening for discover, connect, etc?
Is it explained somewhere or did I oversee it in the docs ?

**Comment by VandeurenGlenn** [comment]
Oh I see
https://github.com/libp2p/js-libp2p/blob/760d8b4c3a341bffccc64c4dd4a83ef205ddf3bf/src/upgrader.js#L73

Way over my head 😅 
Never worked with proxy's

**Comment by vasco-santos** [comment]
This should be fixed with the latest libp2p release since we do type checking now. Feel free to reopen if this is still a problem

**Comment by aurium** [comment]
It was not solved. Try `ipfs.stats.bw({...})`
