### ISSUE TITLE
peerId doesn't get validated

### ISSUE THREAD

**Issue by a1300** [libp2p/js-libp2p#818]
- **Version**: v0.29.3
- **Platform**: Linux
- **Subsystem**:

#### Steps to reproduce the error:

```bash
git clone https://gist.github.com/a1300/b65b4d39893330a7746a8bb94bbff829 libp2p-no-peerId-validation
cd libp2p-no-peerId-validation
npm install
node index
```

Output
```
(node:15157) UnhandledPromiseRejectionWarning: TypeError: libp2p.peerId.toB58String is not a function
    at new ConnectionManager (/home/a1300/test/gny/libp2p-no-peerId-validation/node_modules/libp2p/src/connection-manager/index.js:60:34)
    at new Libp2p (/home/a1300/test/gny/libp2p-no-peerId-validation/node_modules/libp2p/src/index.js:71:30)
    at Function.create (/home/a1300/test/gny/libp2p-no-peerId-validation/node_modules/libp2p/src/index.js:608:12)
    at main (/home/a1300/test/gny/libp2p-no-peerId-validation/index.js:28:33)
    at Object.<anonymous> (/home/a1300/test/gny/libp2p-no-peerId-validation/index.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by vasco-santos** [comment]
We will be working on improving the configuration of libp2p per #576 . We should look into providing better feedback for the mandatory options by then

**Comment by vasco-santos** [comment]
With the new release with type definitions, this should not happen anymore. Feel free to reopen if this is still a problem
