### ISSUE TITLE
Errors using DHT as peer disconnects

### ISSUE THREAD

**Issue by HexaField** [libp2p/js-libp2p#834]
Here are a couple errors I have seen while trying to put to the DHT immediately after a peer disconnects. Package versions are shown in errors.

```
index.min.js:2 Uncaught (in promise) Error: stream ended before 1 bytes became available
    at index.min.js:2
    at :8080/async https:/unpkg.com/libp2p@0.29.4/dist/index.min.js:2
    at async c (index.min.js:2)
    at async Object.t.read (index.min.js:2)
    at async e.exports (index.min.js:2)
    at async i.p [as _newStream] (index.min.js:2)
    at async i.newStream (index.min.js:2)
    at async e.exports.sendRequest (create-browser-e2b3baae.js:6)
    at :8080/async http:/localhost:8080/web_modules/common/create-browser-e2b3baae.js:6
    at :8080/async http:/localhost:8080/web_modules/common/create-browser-e2b3baae.js:6
```

```
Uncaught (in promise) AggregateError: 
    Error: peer is not available
        at l.<anonymous> (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:363195)
        at l.n.emit (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:217949)
        at l.onevent (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:329269)
        at l.onpacket (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:328953)
        at l.<anonymous> (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:330969)
        at l.n.emit (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:217949)
        at l.ondecoded (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:320475)
        at h.<anonymous> (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:330969)
        at h.n.emit (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:217949)
        at h.add (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:216180)
    Error: peer is not available
        at l.<anonymous> (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:363195)
        at l.n.emit (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:217949)
        at l.onevent (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:329269)
        at l.onpacket (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:328953)
        at l.<anonymous> (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:330969)
        at l.n.emit (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:217949)
        at l.ondecoded (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:320475)
        at h.<anonymous> (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:330969)
        at h.n.emit (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:217949)
        at h.add (https://unpkg.com/libp2p-webrtc-star@0.20.2/dist/index.min.js:2:216180)
    at https://unpkg.com/libp2p@0.29.4/dist/index.min.js:2:516628
```

**Comment by vasco-santos** [comment]
@HexaField can you create a test that replicates this issue? It would be great to help with debugging to start with that

**Comment by maschad** [comment]
Closing due to staleness
