### ISSUE TITLE
Failed using with `datastore-level`

### ISSUE THREAD

**Issue by Leask** [libp2p/js-libp2p#970]
Failed while use with `datastore-level`.

- **Version**:

Latest Version

- **Platform**:

All platform

#### Severity:

Critical

#### Description / Steps to reproduce the error:

```javascript
    const Libp2p = require('libp2p')
    const TCP = require('libp2p-tcp')
    const MPLEX = require('libp2p-mplex')
    const { NOISE } = require('libp2p-noise')
    const LevelStore = require('datastore-level')

    const node = await Libp2p.create({
        modules: {
            transport: [TCP],
            streamMuxer: [MPLEX],
            connEncryption: [NOISE]
        },
        datastore: new LevelStore('path/to/store'),
        peerStore: {
            persistence: true,
            threshold: 5
        }
    })
    await node.start();
```

Error:

```
/data/xuxu/Leask/bistrot/node_modules/datastore-level/src/index.js:256
    return levelIteratorToIterator(this.db.iterator(iteratorOpts))
                                           ^
TypeError: Cannot read property 'iterator' of undefined
    at LevelDatastore._query (/data/xuxu/Leask/bistrot/node_modules/datastore-level/src/index.js:256:44)
    at LevelDatastore.query (/data/xuxu/Leask/bistrot/node_modules/datastore-level/src/index.js:176:19)
    at PersistentPeerStore.start (/data/xuxu/Leask/bistrot/node_modules/libp2p/src/peer-store/persistent/index.js:86:47)
    at Libp2p._onStarting (/data/xuxu/Leask/bistrot/node_modules/libp2p/src/index.js:619:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Libp2p.start (/data/xuxu/Leask/bistrot/node_modules/libp2p/src/index.js:363:7)
    at async /data/xuxu/Leask/bistrot/rumdev.js:43:5
```

**Comment by maschad** [comment]
Closing due to staleness
