### ISSUE TITLE
Huge dial errors

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p#996]
```ts
libp2p.dial(peer)
```

Produces huge wrongly formated errors.

```

    Error: stream ended before 1 bytes became available
        at /home/lion/Code/eth2.0/lodestar/node_modules/it-reader/index.js:37:9
        at runMicrotasks (<anonymous>)
        at decoder (/home/lion/Code/eth2.0/lodestar/node_modules/it-length-prefixed/src/decode.js:113:22)
        at first (/home/lion/Code/eth2.0/lodestar/node_modules/it-first/index.js:11:20)
        at Object.exports.read (/home/lion/Code/eth2.0/lodestar/node_modules/multistream-select/src/multistream.js:31:15)
        at module.exports (/home/lion/Code/eth2.0/lodestar/node_modules/multistream-select/src/select.js:21:19)
        at Upgrader._encryptOutbound (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.js:397:36)
        at Upgrader.upgradeOutbound (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.js:176:11)
        at ClassIsWrapper.dial (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p-tcp/src/index.js:49:18)
AggregateError: 
    Error: stream ended before 1 bytes became available
        at /home/lion/Code/eth2.0/lodestar/node_modules/it-reader/index.js:37:9
        at runMicrotasks (<anonymous>)
        at decoder (/home/lion/Code/eth2.0/lodestar/node_modules/it-length-prefixed/src/decode.js:113:22)
        at first (/home/lion/Code/eth2.0/lodestar/node_modules/it-first/index.js:11:20)
        at Object.exports.read (/home/lion/Code/eth2.0/lodestar/node_modules/multistream-select/src/multistream.js:31:15)
        at module.exports (/home/lion/Code/eth2.0/lodestar/node_modules/multistream-select/src/select.js:21:19)
        at Upgrader._encryptOutbound (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.js:397:36)
        at Upgrader.upgradeOutbound (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.js:176:11)
        at ClassIsWrapper.dial (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p-tcp/src/index.js:49:18)
    at maybeSettle (/home/lion/Code/eth2.0/lodestar/node_modules/p-some/index.js:31:11)
    at /home/lion/Code/eth2.0/lodestar/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

In the above error `e.message` starts with a newline character and contains the entire stack trace. See below I'm printing `{ emessage: e.message }` after catching an error from dial()

```
{
  emessage: '\n' +
    '    Error: stream ended before 1 bytes became available\n' +
    '        at /home/lion/Code/eth2.0/lodestar/node_modules/it-reader/index.js:37:9\n' +
    '        at runMicrotasks (<anonymous>)\n' +
    '        at decoder (/home/lion/Code/eth2.0/lodestar/node_modules/it-length-prefixed/src/decode.js:113:22)\n' +
    '        at first (/home/lion/Code/eth2.0/lodestar/node_modules/it-first/index.js:11:20)\n' +
    '        at Object.exports.read (/home/lion/Code/eth2.0/lodestar/node_modules/multistream-select/src/multistream.js:31:15)\n' +
    '        at module.exports (/home/lion/Code/eth2.0/lodestar/node_modules/multistream-select/src/select.js:21:19)\n' +
    '        at Upgrader._encryptOutbound (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.js:397:36)\n' +
    '        at Upgrader.upgradeOutbound (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.js:176:11)\n' +
    '        at ClassIsWrapper.dial (/home/lion/Code/eth2.0/lodestar/node_modules/libp2p-tcp/src/index.js:49:18)'
}
```

This makes it very hard to render nice error messages in log driven applications

- **Version**:
`libp2p` v0.32.4

**Comment by BigLep** [comment]
@dapplion : thanks for reporting.  Given current resourcing, I don't see PL maintainers getting to this soon.  A contribution is welcome here. Do you want to take this on?

**Comment by achingbrain** [comment]
At the time this issue was opened, libp2p used [p-any](https://www.npmjs.com/package/p-any) to [dial every valid multiaddr](https://github.com/libp2p/js-libp2p/blob/1c2e4d89acbbd657f4dd44c93933d1a531a059f8/src/dialer/dial-request.js#L66) a given peer had which is where the error is coming from.

`p-any` depends on [p-some](https://www.npmjs.com/package/p-some), which depends on [aggregate-error](https://www.npmjs.com/package/aggregate-error).

Right now we use a regular [Promise.any](https://github.com/libp2p/js-libp2p/blob/master/src/connection-manager/dialer/dial-request.ts#L85) instead, so the above should not be happening any more.

The [AggregateError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError) docs imply that the `.message` field should be a simple string rather than the concatenated stack traces of all the aggregated errors, so if it's still an issue I'd open a PR on the [aggregate-error repo](https://github.com/sindresorhus/aggregate-error) to bring it more in line with the spec/MDN docs.  There are a couple of relevant issues open on that repo already.
